### ISSUE TITLE
Option to enable footer when highlighting a single element.

### ISSUE THREAD

**Issue by bombsite** [kamranahmedse/driver.js#100]
Currently the footer buttons only show up when there are steps, I would like to enable showing the Done button when there is only a single highlight.

**Comment by bombsite** [comment]
#101 
Please advise if there are outstanding issues to resolve.

**Comment by kamranahmedse** [comment]
Hey, thanks for opening the issue but we are not planning to add that. You can do that by manually modifying the popover in one of the hooks.
