### ISSUE TITLE
[Feature request] Option to override animation duration

### ISSUE THREAD

**Issue by tama3bb** [kamranahmedse/driver.js#104]
The animation duration, which is 400 ms by default, is slow for some use cases. How about adding an option to specify the animation duration? I don't know how to apply the duration in the css file, though.

**Comment by kamranahmedse** [comment]
There hasn't been many requests for this so I am going to close it for now. But this should be easy to implement, all you have to do is [make it configurable here](https://github.com/kamranahmedse/driver.js/blob/master/src/highlight.ts#L59). Feel free to submit a PR.

**Comment by rharkor** [comment]
Can you reopen the issue, I think this is pretty important

**Comment by mfrizqi** [comment]
Up for this to be reopen, somewhat i feel if we can adjust the duration variable would be great and flexible!
