### ISSUE TITLE
Lazy element selector evaluation.

### ISSUE THREAD

**Issue by ArnaudLevaufre** [kamranahmedse/driver.js#107]
Hello,

It would be really nice to have a way of defining steps with element that are not yet present on the page. In my use case, I walk the user through multiple steps untils the user opens a popup that is not present at page load nor at drive instantiation time. If element is still not present when user tries go to this step it could simply be skipped. I guess problems will arise if the last step is skipped, especially regarding the `end tour` button.

Let me know what you think about it.

**Comment by ArnaudLevaufre** [comment]
Yep, it looks like it will do what I want.

**Comment by kamranahmedse** [comment]
It is now possible in 0.6.0. Have a look at the [Asynchronous Examples](https://github.com/kamranahmedse/driver.js#asynchronous-actions--demo) demo.

Feel free to re-open if that doesn't solve it for you.

**Comment by alessandro308** [comment]
I don't understand how the example can help. If the element doesn't exists on the page, line 388 of index.js
```
    const domElement = isDomElement(querySelector) ? querySelector : this.document.querySelector(querySelector);
```
fails during init and the step is no shown at all even if during the onNext the element is created
