### ISSUE TITLE
Any support for import of driver in React?

### ISSUE THREAD

**Issue by jeffreyabarrios** [kamranahmedse/driver.js#11]

**Comment by kamranahmedse** [comment]
Yes, it is planned. Hopefully in the coming weekend. 

Just want to [finish this rewrite](https://github.com/kamranahmedse/driver.js/pull/10) so that we have it out of the way once and for all, then we can focus on the wrappers :)

**Comment by roelvan** [comment]
I am having a Babel import problem, any idea how to use this? I am using Vue client and this is my import statement: `import Driver from ''driver.js"`. My error:
```
This dependency was not found:

* driver.js in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"/Users/roel/Repos/dsmtw-v2-engine/node_modules/.cache/cache-loader"}!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/lobby.vue

To install it, you can run: npm install --save driver.js
```

**Comment by wave52** [comment]
you can
`import Driver from 'driver.js/dist/driver.min.js'`

**Comment by kamranahmedse** [comment]
@roelvan could you please try now? there was an issue with `main` definition in `package.json`. It should be fixed now

**Comment by roelvan** [comment]
> @roelvan could you please try now? there was an issue with main definition in package.json. It should be fixed now

Yep that did the trick. Now it works.

**Comment by kamranahmedse** [comment]
Cool, thanks

**Comment by Rutulpatel7077** [comment]
It's disappearing when life cycle render the main component.

**Comment by Attrash-Islam** [comment]
I've used driver.js with `require` in a ES Module project and it worked very well. Try it, if it's working then there's no need to use the `import` syntax.
