### ISSUE TITLE
How to implement a fast transition?

### ISSUE THREAD

**Issue by ArtemPavliienko** [kamranahmedse/driver.js#111]
I need to implement transition on the windows like in the Intro js.

Example: [http://joxi.ru/L21QoV1H80nw42]()

How do I implement this?

I tried to write it like this, but it didn't work out

driver.defineSteps([
            {
                element: '#Step1',
                popover: {
                    title: '<h4 class="titleDrive">WHAT IS SPAM FILTER PRO ?</h4>',
                    description: 'текст <span class="go"></span>',
                    position: 'bottom'
                }
            },
{
                element: '#Step2',
                popover: {
                    title: '<h4 class="titleDrive">WHAT IS SPAM FILTER PRO ?</h4>',
                    description: 'текст 2 <span class="go"></span>',
                    position: 'bottom'
                }
            }]

$('#driver-popover-item .go').click(function () {
                driver.reset();
                driver.start(defineSteps = 2);
            });

**Comment by raphael22** [comment]
- Your exemple is a link to this issue :/
- Your code example should be formatted

Otherwise you can fork it and change ```$animation-ms``` in driver.scss, and ```ANIMATION_DURATION_MS``` in common/constants with desired value.

**Comment by andersonba** [comment]
It would be nice if we can override the `ANIMATION_DURATION_MS` value via options, without having to compile the code.

**Comment by kamranahmedse** [comment]
Thank you for reporting. There is already an issue open for that https://github.com/kamranahmedse/driver.js/issues/104.
