### ISSUE TITLE
Driver.js inside a scrolling div

### ISSUE THREAD

**Issue by ericgruby01** [kamranahmedse/driver.js#112]
Hi,

I'm trying to use Driver.js inside a div that has `overflow-y: auto;`, but it's kinda buggy... See [this pen](https://codepen.io/ericgruby/pen/ERGpYW), please. _Step 1_ seems fine, but the other steps go wild.

Am I missing something? Is there some part of the documentation I didn't read?

Sorry if this is a duplicate.

**Comment by raphael22** [comment]
My PR #127 seems to fix it.
[forked pen with PR](https://codepen.io/Raphael/pen/EeLmvE)

**Comment by JazudyZura** [comment]
I can only use it on a Url page. When I turn the page, the "next", "previous" buttons will fail.

**Comment by MrSeaWave** [comment]
@raphael22, hi raphael22, I think it's not be fixed, I also get this error , you can see this [issue](https://github.com/kamranahmedse/driver.js/issues/232#issue-593078047)
