### ISSUE TITLE
[Feature Request] - Support of driver.js in Ionic app

### ISSUE THREAD

**Issue by briskettacos** [kamranahmedse/driver.js#117]
Not sure if this was covered before. Do you have an example of how to use it in SPA? i am having issues using driver.js with my ionic app

**Comment by kamranahmedse** [comment]
It should work just fine with any SPA frameworks. Please re-open with the reproducing plunkr/the error that you are getting.

**Comment by jonnysmith1981** [comment]
I also get this behaviour. No errors are displayed in the console, but in the element inspector you can see the new div getting added then immediately removed.

**Comment by Attrash-Islam** [comment]
I'm using it with React. It's working perfect. In a framework environment you should call the driver when you have the elements stable in the page. (Wrote a React Wrapper that works 💯)

**Comment by jonnysmith1981** [comment]
I posted an update on another ticket as i had managed to get it working with an Ionic app. The issue for me was to call `event.stopPropogation()` after calling `driver.highlight()`
