### ISSUE TITLE
Animated driver does not work on SVG children

### ISSUE THREAD

**Issue by remibd** [kamranahmedse/driver.js#123]
Hi!

When highlighting an element that’s inside a `<svg>` tag, it does not get highlighted and the stage is rendered *over* the element, effectively hiding it. Here’s a [codepen](https://codepen.io/anon/pen/qyrLQE) reproducing the bug: oddly, it works all right with a static Driver.

Might be related to #95.

# How to reproduce
1. Create an element inside a `<svg>` tag.
2. Highlight it with an animated Driver.

## Expected result
The highlighted element is rendered *over* the stage and overlay.

## Actual result
The highlighted element is rendered *below* the stage and overlay.

# Workaround
Right now, I have found nothing satisfying; my best solution is to temporarily render the stage as a bordered rectangle.

```javascript
function nextBorderedStage(driver) {
    driver.preventMove();
    driver.moveNext();
    this.borderedStage();
}

function previousBorderedStage(driver) {
    driver.preventMove();
    driver.movePrevious();
    this.borderedStage();
}

function borderedStage() {
    const stage = document.getElementById('driver-highlighted-element-stage');
    stage.style.backgroundColor = 'transparent';
    stage.style.border = '2px solid white';
}
```

and call the `nextBorderedStage()` and `previousBorderedStage()` functions in `onNext()` and `onPrevious()` handlers.

**Comment by kamranahmedse** [comment]
Thanks for opening the issue. For the animated driver, yes, we have this limitation with the SVG children. You can use the non-static version the given workaround, whatever works for you.
