### ISSUE TITLE
In no animation mode, click on overlay pass through

### ISSUE THREAD

**Issue by ValdoGhafoor** [kamranahmedse/driver.js#129]
Hi,
I have driver.js 0.7.1
When I trigger a multistep tutorial  with no animation mode, I can click on buttons, links ... etc behind the overlay

**Comment by kamranahmedse** [comment]
That is a known issue. To tackle the z-index stacking context issues, we don't have the overlay in the non-animated version and it is achieved by simply putting an outline around the stage, which does not block the clicks and thus clicks are passed through. 

We could use [focus-trap](https://github.com/davidtheclark/focus-trap), for example, to achieve that behavior but it is intentionally left-out to avoid the bloat. You can however use it in [one of the available hooks](https://github.com/kamranahmedse/driver.js#driver-definition) to achieve that.
