### ISSUE TITLE
handle element size changes - expose and/or document overlay.refresh()

### ISSUE THREAD

**Issue by zevdg** [kamranahmedse/driver.js#130]
In my tour, I have an element that grows over time.  When driver.js was highlighting it, it grew beyond the confines of the lightbox.  I was able to figure out how to fix this by digging through the source code and finding overlay.refresh() - see [this demo pen](https://codepen.io/zevdg/pen/xywNZz).

Making overlay.refresh() part of the documented API seems like the reasonable thing to do, at least until [ResizeObserver](https://developers.google.com/web/updates/2016/10/resizeobserver) is [more widely supported](https://caniuse.com/#feat=resizeobserver).

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. It has been implemented in the latest release (0.9.2). 
Please have a look and re-open if the issue persists. Thanks!
