### ISSUE TITLE
Driver is not a constructor error

### ISSUE THREAD

**Issue by AHerreraDev** [kamranahmedse/driver.js#131]
Hello friends,

I am now getting the following error:

_**Uncaught TypeError: Driver is not a constructor
    at onLoad ((index):206)**_

Code:
> <script src="https://unpkg.com/driver.js/dist/driver.min.js"></script>
> Link to ->  href="https://unpkg.com/driver.js/dist/driver.min.css" />
> 
> const driver = new Driver();

**Comment by AHerreraDev** [comment]
It was working as of yesterday Thursday Oct 11th.

**Comment by kamranahmedse** [comment]
Fixed. Thank you for reporting.
