### ISSUE TITLE
Only adding elements to body tag in index.html in Angular application

### ISSUE THREAD

**Issue by hajimurtaza** [kamranahmedse/driver.js#132]
Angular CLI - 6.1.3
I am trying to use in an angular application

header.component.ts
const driver = require('../../../../../node_modules/driver.js/dist/driver.min.js');
let Driver = new driver;

NgOnInit(){
Driver.highlight({
      element: '#step1',
      popover: {
        title: 'Title for the Popover',
        description: 'Description for it',
      }
    });
}

header.component.html
<nav id="step1">

Implementing here straight out of the box
https://github.com/Ismaestro/angular6-example-app

![image](https://user-images.githubusercontent.com/29270236/46891290-5fc3f100-ce37-11e8-803d-4394018bc9f2.png)

**Comment by kamranahmedse** [comment]
It looks like you forgot to import the CSS. Try again with below imports on top of the component

```javascript
import Driver from 'driver.js';
import 'driver.js/dist/driver.min.css';
```
