### ISSUE TITLE
[Feature request] Option to show "close" button also in single-step ride

### ISSUE THREAD

**Issue by Rombecchi** [kamranahmedse/driver.js#134]
Hi to everyone,
it's unusual, I know,... but sometimes some visitors don't understand that they can close the single-step ride (aka: Highlighting a Single Element) just clicking outside the box or hitting the ESC key.
So I want to be more explicit giving the chance to add the close button phisically onto the popover box.
It's as far as setting the display:block to the ".driver-popover-footer" class and  ".driver-btn-group" back to "display:none"
Thanks very much.

**Comment by cuzi** [comment]
I also need that feature..
If you show allowClose: false and a single step there is no way that user can close the popover

**Comment by kamranahmedse** [comment]
It is in the roadmap and will be there in the next release

**Comment by kamranahmedse** [comment]
This has been added in the [0.9.3 release](https://github.com/kamranahmedse/driver.js/releases/tag/0.9.3). Close button will be shown on the popover for single highlights also, which can be removed by `showButtons: false` in the options
