### ISSUE TITLE
Provide unminified distribution files

### ISSUE THREAD

**Issue by schutze** [kamranahmedse/driver.js#136]
Unminified distribution files should be provided in the dist folder for those who want to bundle and minify themselves.

**Comment by schutze** [comment]
But I don't use the same packager/bundler tool as you.  No matter, I couldn't get this plugin to work for me anyway so I'll be using another.

**Comment by kamranahmedse** [comment]
> I couldn't get this plugin to work

What was the problem, could you elaborate please so that it may be fixed for others?

**Comment by schutze** [comment]
Not much happened... the background appeared, no popovers displayed, and then the background disappeared.  No obvious errors in the console.

**Comment by schutze** [comment]
@kamranahmedse The other plugins I tried also have a few issues so I'd like to try to get Driver working for me.  Maybe there's some conflict somewhere.  To help troubleshoot, would it be possible for you to post the unminified files?

**Comment by schutze** [comment]
I finally figured out why Driver wasn't working after reading #57.  But, I would still like to have unminified files if that's not too much trouble.
