### ISSUE TITLE
not working properly with 'addEventListner'

### ISSUE THREAD

**Issue by kei0719** [kamranahmedse/driver.js#14]
since **0.2.0** driver.js was not working to be properly with `addEventLister` method, just blinking.

I tested with **Firefox** and **Google Chorme** on Mac, either same results..

```js
var driver = new Driver();
document.getElementById('btn1')
        .addEventListener('click', function(event) {
  
    driver.highlight({
      element: '#form1',
      popover: {
        title: 'Title for the Popover',
        description: 'Description for it',
      }
    });
});
```

![abcdd](https://user-images.githubusercontent.com/1003334/37378927-8f28f8f6-2774-11e8-9ccb-51983069ac41.gif)

**Comment by aulisius** [comment]
Taking from the demos,

```
.addEventListener('click', (e) => {
      e.preventDefault();

      singleDriverWithPopoverPosition.highlight({
        element: '#single-element-with-popover-position',
        popover: {
          title: 'Did you know?',
          description: 'You can add HTML in title or description also!',
          position: 'top'
        }
      });
    });
```

Maybe you can also try adding the `event.preventDefault()` before calling the driver.

**Comment by kamranahmedse** [comment]
Hey @kei0719 you need to add `event.stopPropagation()`

```
var driver = new Driver();
document.getElementById('btn1')
        .addEventListener('click', function(event) {
    event.stopPropagation();

    driver.highlight({
      element: '#form1',
      popover: {
        title: 'Title for the Popover',
        description: 'Description for it',
      }
    });
});
```

Also if the button is anchor with `href="#"', you may also have to do `event.preventDefault()` to make the page not scroll to top

**Comment by kamranahmedse** [comment]
Please reopen if that doesn't solve the issue.

**Comment by JamoCA** [comment]
I was encountering similar UI flash using a jquery w/a button.  I shouldn't have to add `stopPropagation` for this, should I?  (I've never had to do this before when combined with other event listeners regardless of whether using vanilla JS or jQuery.)

    $('body').on('click', '.startDemoBtn', function(e){
        // e.stopPropagation(); /* This won't work unless this line is unremmed */
        startDriver();
    });
    
    <button type="button" class="startDemoBtn">startDemo</button>

**Comment by kamranahmedse** [comment]
Hey, yes it is mentioned in the readme also, you need to add that. It is how the `driver` is implemented. Since the element is located out of the element to be highlighted, clicking this displays the overlay and immediately catches this click event if you don't use `e.stopPropagation()` and clears it. I need to handle it better but for now, you need to add this
