### ISSUE TITLE
Handling of touch events seems to be missing

### ISSUE THREAD

**Issue by bm-stschneider** [kamranahmedse/driver.js#141]
In chrome the touch events are fired prior to the mouse/click emulation. This may lead to a click outside of the next button, closing the tour.
Can you extend the event handling to include touch events for mobile devices please.
Or this may be a bug in some way.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. We are already handling the touch events, however I did found and fixed a bug in the latest release (0.9.2) where tap was closing the tour. Could you please try with that and see if it solves the issue?

Please re-open if the issue still persists. Thanks!

**Comment by joedeveloper** [comment]
I am seeing this behavior on the current demo - at least I thought I was, until I turned on touch visualization in the android developer options. The buttons are well neigh impossible to hit with my fat fingers on a Sony Xperia XZ3.

Making the buttons bigger on the demo for mobile clients would avoid the impression, which I had,  of this being broken on mobile.

**Comment by fabianmarcus** [comment]
Hey, really nice lib! 

However, unfortunately touch still does not seem to be working in current Version 0.9.5, is it?

**Comment by bm-stschneider** [comment]
try 0.9.3
