### ISSUE TITLE
Element to highlight not found, There are no steps defined to iterate

### ISSUE THREAD

**Issue by mohithkovela** [kamranahmedse/driver.js#145]
Implemented in an ionic app.

HTML:
<ion-tab id="tab2">TabTitle</ion-tab>

Script:
const driver = new Driver();
    driver.defineSteps([
      {
        element: "#tab1",
        popover: {
          title: "Title on Popover",
          description: "Body of the popover"
        }
      },
      {
        element: "#tab2",
        popover: {
          title: "Title on Popover",
          description: "Body of the popover"
        }
      }
    ]);
driver.start();

Errors while running:
1. Element to highlight #tab2 not found
2. There are no steps defined to iterate

**Comment by kamranahmedse** [comment]
Thank you for opening the issue. I am not able to reproduce it. Please submit [a codesandbox example](https://codesandbox.io/s/llp1rypn6m) so that we may help you better.

**Comment by ashish-r** [comment]
I am also encountering this issue once in a while. http://guided-tour.uat.coverfox.com/term-insurance/quotes/b52b36d7-e3a0-470e-b574-797d83efd07d/?type=std

**Comment by michaeldong** [comment]
Maybe all your "steps" invalid.  
Code: 
`
 for (let counter = 0; counter < steps.length; counter++) {
      const element = this.prepareElementFromStep(steps[counter], steps, counter);
      if (!element) {
        continue;
      }

      this.steps.push(element);
    }
`
maybe "prepareElementFromStep" return null, your steps be ignored.

**Comment by PriyaAgr11** [comment]
I am also facing the same issue which @mohithkovela has highlighted.
I have a loop using *ngFor in html and append id using index, Eg - 
<ion-icon slot="icon-only" name="arrow-redo-outline" [id]="'share'+i"></ion-icon>

In Ts file -

driver.defineSteps( [
      {
        element: "#share0",
        popover: {
          title: "Share Your Soup",
          description: "Share any Soup on social media or by email.",
          position: "left",
        },
      }
]);
driver.start();

But this is giving Element to highlight #share0 not found.

How to resolve this?

**Comment by 1Rone11** [comment]
why occur this error is  forget the browser DOM  Loading mechanism and learn the  Lifecycle Hooks of Vue.
u should write this code block in "onMounted". wait for the DOM loaded.

**Comment by 1Rone11** [comment]
> Implemented in an ionic app.
> 
> HTML: TabTitle
> 
> Script: const driver = new Driver(); driver.defineSteps([ { element: "#tab1", popover: { title: "Title on Popover", description: "Body of the popover" } }, { element: "#tab2", popover: { title: "Title on Popover", description: "Body of the popover" } } ]); driver.start();
> 
> Errors while running:
> 
> 1. Element to highlight #tab2 not found
> 2. There are no steps defined to iterate

why occur this error is forget the browser DOM Loading mechanism and learn the Lifecycle Hooks of Vue.
u should write this code block in "onMounted". wait for the DOM loaded.
