### ISSUE TITLE
[Feature request] On reset add clicked element

### ISSUE THREAD

**Issue by cuzi** [kamranahmedse/driver.js#146]
Any chance that onReset Function will get also the clicked element ?
In that way i'll could indicate where the user clicked to close the tour and improve my use in the driver for the end user.

Thanks

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. There are more simplified hooks which give you more control over the popover and the whole lifecycle. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
