### ISSUE TITLE
Typos on Readme.md

### ISSUE THREAD

**Issue by Kangcor** [kamranahmedse/driver.js#147]
There are some typo in the readme, in Driver definition and Step definition:
```
onNext: (Element) => {},                    // Called when moving to next step on any step
onPrevious: (Element) => {},                // Called when moving to next step on any step
```

Should be:
```
onNext: (Element) => {},                    // Called when moving to next step on any step
onPrevious: (Element) => {},                // Called when moving to previous step on any step
```
Thanks for this library, works like a charm!

**Comment by Attrash-Islam** [comment]
@Kangcor Are you proposing a PR or I can take it? 😃

**Comment by Kangcor** [comment]
If you don't mind let me do it, I could use the experience of the process
in this easy PR. Thanks!

**Comment by Kangcor** [comment]
Created pull request [PR](https://github.com/kamranahmedse/driver.js/pull/148)

**Comment by kamranahmedse** [comment]
Thanks
