### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by bm-stschneider** [kamranahmedse/driver.js#150]
Chrome in the current version and in the device emulation mode drops a Uncaught TypeError: Cannot read property 'style' of undefined. Firefox works normal.

![image](https://user-images.githubusercontent.com/30625381/53625557-bd4cb480-3c03-11e9-9998-dde28c2731f3.png)

**Comment by kamranahmedse** [comment]
Thank you for reporting the issue. I am not able to reproduce it. Could you please provide a reproducing example/steps to reproduce?

**Comment by poncot** [comment]
Hi, I have the same problem on my project created by Vue CLI.
You can reproduce it in an initial Vue CLI project.
`vue create hello-world`
`cd hello-world`
`npm install --save driver.js`
add some code of driver.js to src/App.vue
`vue serve`

**Comment by MarkGStacey** [comment]
Also seeing this in a Vue CLI project (on top  of Quasar) - is this related to Vue?

**Comment by kamranahmedse** [comment]
Could you please link the codesandbox example?

**Comment by MarkGStacey** [comment]
Well thats annoying, in sandbox with just Vue, it works. I'll have to see about getting Quasar up in Sandbox
https://codesandbox.io/s/vqpm16v74y

**Comment by side9527** [comment]
I've found a solution.
like this 
@click..prevent.stop="openGuide"

**Comment by kamranahmedse** [comment]
This should be fine now in the [latest release](https://github.com/kamranahmedse/driver.js/releases/tag/0.9.5). Can you please try with `0.9.5` and see if it fixes the issue?

**Comment by bm-stschneider** [comment]
My steps where as follows:
* Open Chrome
* Open Dev Tools
* Enable Device Emulatution
* Go to page with a configured tour

**Comment by kamranahmedse** [comment]
It should be fine now in `0.9.5` – please retry and reopen if you still face the issue. Thanks.

**Comment by bm-stschneider** [comment]
ok now when I hit next the tour ends prematurely

**Comment by kamranahmedse** [comment]
Okay I was able to reproduce it, will look into it soon. Thanks!

**Comment by bm-stschneider** [comment]
Any update on this?

**Comment by marvhock** [comment]
The current error (after 0.9.5) seems to was present on older versions already - 0.9.5 just fixed another error which got triggered before the current issue.

What I noticed is 1. It only occurs on mobile, and 2. The onClick handler is triggered by click and touchstart.

So my guess is, click on mobile triggers clickHandler for step 1, then triggers clickHandler by touchstart and closes step2

**Comment by kamranahmedse** [comment]
This should be fine in 0.9.6. Please let me know if you still face issues. Thank you!

**Comment by Master0606** [comment]
![image](https://user-images.githubusercontent.com/39380398/65850314-a95e6200-e34e-11e9-9b7a-686c3472c883.png)
Hello, how are you?
How can I fix this issue?
