### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by yaozaiyu** [kamranahmedse/driver.js#151]
1. Select option cannot be selected in your box,Options will be posterior to the second line
![1551686838 1](https://user-images.githubusercontent.com/25170955/53718956-a920e580-3e97-11e9-8881-37b6261bd2e4.jpg)

**Comment by yaozaiyu** [comment]
> 1. Select option cannot be selected in your box,Options will be posterior to the second line
>    ![1551686838 1](https://user-images.githubusercontent.com/25170955/53718956-a920e580-3e97-11e9-8881-37b6261bd2e4.jpg)

**Comment by kamranahmedse** [comment]
Hey, thank you for reporting it. You can do that by giving your dropdown a higher `z-index` than the overlay stage. If you have a public link or a demo somewhere, I can help you with it. However, try playing with z-index and you will figure it out.
