### ISSUE TITLE
I want to add new Custom Button on Popover. How to add new buttons and also How to add click event on to it?

### ISSUE THREAD

**Issue by rahuljavascript1** [kamranahmedse/driver.js#152]
Hi, I am using driver.js in my react application. I need to add a new custom button on the popover. And also that button will have a click event. I shall be thankful to you for this. I tried using the template string literal in the "description " of "popover " but the onClick function is not working. Let me know if you have any solution for this.

**Comment by joshua88m** [comment]
Dealing with the same issue here.

I cant call the onclick function. it just blinks on the screen. Any updates?

**Comment by Attrash-Islam** [comment]
If there's no `event.stopPropogation` in the library code (Which should be the case) then you can catch the clicks on any elements by -> 

```js
document.addEventListener('click', ({target}) => {})
```

**Comment by Attrash-Islam** [comment]
Regards the buttons creations I used to hide the footer and to create my buttons by adding them to the description html template. In that way you're not forced to the template of DriverJS.

**Comment by kamranahmedse** [comment]
Look at the [custom button docs page](https://driverjs.com/docs/buttons/).

We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
