### ISSUE TITLE
I want to close overlay on click on description/title only. 

### ISSUE THREAD

**Issue by rahul1si12is035** [kamranahmedse/driver.js#153]
I am using this library in my react app. I want to close overlay on click on description/title only. How to manually call the close function. Is there any method to call the close function. Thanks in advance.

**Comment by Attrash-Islam** [comment]
This is the method that you need:

```js
driver.reset(); // Resets the overlay and clears the screen
```

**Comment by kamranahmedse** [comment]
Thanks @Attrash-Islam

**Comment by rahul1si12is035** [comment]
Thanks. It worked
