### ISSUE TITLE
Does not work in Ionic (Angular-based) application

### ISSUE THREAD

**Issue by jonnysmith1981** [kamranahmedse/driver.js#156]
I have set up a really simple example based off the demo:

[https://github.com/jonnysmith1981/ionic-driverjs](https://github.com/jonnysmith1981/ionic-driverjs)

When the demo runs, if you click the blue button it should highlight the div however nothing happens. If you open the browser's developer tools, you can see the `<div id="driver-page-overlay">` div being added just above the `</body>` tag, but it is immediately removed.
No errors are thrown, it just seems to fail silently.

**Comment by trayvon2017** [comment]
May be you can try **stop event propagation**

**Comment by jonnysmith1981** [comment]
@trayvon2017  Nailed it! Thanks a lot.

**Comment by Juanperezc** [comment]
I have the same issue, 
What did you do to solve it, how did you call that event?

**Comment by kamranahmedse** [comment]
@Juanperezc make sure to call `e.stopPropagation()` on the click event that triggers the driver
