### ISSUE TITLE
2 values for offset needed

### ISSUE THREAD

**Issue by st-schneider** [kamranahmedse/driver.js#157]
If you pick position mid-center, the offset value is added to x and y so you can only change position diagonally.

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
