### ISSUE TITLE
Bug(Ionic) Driver highlighted element 

### ISSUE THREAD

**Issue by Juanperezc** [kamranahmedse/driver.js#158]
Hi
I have the following problem when I run the highlight on ionic apparently for more than increasing the z-index of the driver-highlighted-element class the element is still below the white box

![image](https://user-images.githubusercontent.com/16789435/55818258-39200380-5ac4-11e9-8f0c-8ac4b0267cc9.png)

**Comment by kamranahmedse** [comment]
It has something to do with the way your [elements are positioned](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) Please provide a reproducing example on [codesandbox](https://codesandbox.io/s/vanilla) or [plunkr](plunkr.co) so that we can help you better. Or use the non-animated version with `animate` set to `false`.

**Comment by Juanperezc** [comment]
Thank you, I set the animate to false and solved.

**Comment by kapooramit** [comment]
This solved my issue too. However, I love the animation. I will rewrite the code to get this working.

**Comment by PhantomYdn** [comment]
Thanks! Disabling of animation also helped me. @kamranahmedse , any possibility to fix the issue with animated version?

**Comment by PhantomYdn** [comment]
Fix was provided in comments of #133

**Comment by chaitanya71998** [comment]
> It has something to do with the way your [elements are positioned](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) Please provide a reproducing example on [codesandbox](https://codesandbox.io/s/vanilla) or [plunkr](plunkr.co) so that we can help you better. Or use the non-animated version with `animate` set to `false`.

but on animate set to false, i can click any other clickable elements underneath
https://codesandbox.io/s/funny-heisenberg-91bzb
check here even on highlight i can click reset or highlight buttons
