### ISSUE TITLE
Can't the demo page open? in China

### ISSUE THREAD

**Issue by mingxuan0624** [kamranahmedse/driver.js#159]
Can't the demo page open? in China

**Comment by spsaucier** [comment]
The demo page is down entirely - I suspect because the author made a new website.

**Comment by kamranahmedse** [comment]
It seems to be working fine.
 
![image](https://user-images.githubusercontent.com/4921183/65684862-b2f77980-e071-11e9-8a0c-80e5b81ec4bd.png)

Can you please try https://kamranahmedse.github.io/driver.js
