### ISSUE TITLE
 bottom-left

### ISSUE THREAD

**Issue by Muchwat** [kamranahmedse/driver.js#161]
Please add bottom-left

**Comment by vishwanathovi** [comment]
This is for positioning the pop-over?

**Comment by vishwanathovi** [comment]
I am new to contributing to an open source project. Any open issues in this project that is good for intermediate JS guy like me?

**Comment by Muchwat** [comment]
Yes for positioning the pop-over.

**Comment by vishwanathovi** [comment]
Okay. Will work on this issue then.

**Comment by kamranahmedse** [comment]
Hey, there is already `left-bottom`, please use that.

**Comment by vishwanathovi** [comment]
Got it. Shall I add the current positioning options into the Demo page? currently it only has left, top, bottom & right.

**Comment by vishwanathovi** [comment]
Also, i was thinking of a feature 
   * While highlighting input boxes, allow Enter(key press) as an option to move to the next highlighted button. This will help in building forms that will highlight the current required field for every field.

**Comment by kamranahmedse** [comment]
@vishwanathovi if you want to update the demo page for that, go ahead. 

Regarding the Enter key to move next, I don't think we should have that, it can easily be implemented by anyone who wants that using an event handler in their app.
