### ISSUE TITLE
CommonJS version available?

### ISSUE THREAD

**Issue by swampthang** [kamranahmedse/driver.js#163]
Thanks so much for this library. Would love to use it. I need something like this for an Electron app but am not using Babel and Electron/Node doesn't natively support ES6 modules. My entire app is set up using require statements. Would really love to be able to use this. 
Thanks

**Comment by Attrash-Islam** [comment]
We used it as so `const Driver = require('driver.js');` and it's working with require statements 😃

**Comment by kamranahmedse** [comment]
Thanks @Attrash-Islam. @swampthang it should work fine as suggested by islam - just replace the imports with requires. Let us know if you face any issues.

**Comment by swampthang** [comment]
Thanks so much for the quick reply. Yes, it does work. No errors. I just had to include the css file and all is working great! Thanks again.
