### ISSUE TITLE
How to customize high-lite style to add radius

### ISSUE THREAD

**Issue by suneethar** [kamranahmedse/driver.js#164]
Currently I am not seeing any configuration to style to high-lite, only for popover class is taken, how can i style the highlite, I want it be round than square.

**Comment by Attrash-Islam** [comment]
The highlight box have this selector `#driver-highlighted-element-stage` but unfortunately I tired to add border-radius but didn't work since outline affect such a style.

**Comment by suneethar** [comment]
I am able to override the style using #driver-highlighted-element-stage. But I dint find any configuration to pass class to the highlighted div. I don't want to override using #driver-highlighted-element-stage.
Like popover is taking class, I was searching for highlighted div also.
So that tomorrow if id name changes, there is no changes required in the application

**Comment by Attrash-Islam** [comment]
@kamranahmedse Do you want me to send a PR to add a className for this element?

**Comment by suneethar** [comment]
Yes, I don't have any specific name for it, you can say it as highlitedClassName or whatever make sense for the user to understand.

**Comment by vishwanathovi** [comment]
Is this still open? I feel like a whole lot of new APIs can be created to provide customization of the pop-over and highlight section.
Eg: User can pass CSS through JS for both Pop-over & Highlight through 2 options during the driver creation. 
This will give 100% freedom for the user to decide how he wants to customize the overall driver.js experience.

**Comment by Attrash-Islam** [comment]
Waiting for @kamranahmedse sign. I may prefer to style by the id selector without making the API bigger to keep it simple IMO

**Comment by kamranahmedse** [comment]
We now have `stageRadius` option for this.

Also, we just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
