### ISSUE TITLE
Keyboard navigation is not working if in defineSteps doent have popover

### ISSUE THREAD

**Issue by suneethar** [kamranahmedse/driver.js#165]
In my use case I don't ant to show popover ,its only high lite with description in panel at the bottom, if I remove popover in the defined steps then arrow left and right is not moving the spotlight, only escape closes the tour.
 
In index.js found that below code which is not allowing key handler if there is no popover
if (!highlightedElement || !highlightedElement.popover) {
      return;
    }

I have added opacity: 0 to popover and its working without popover, but not sure whether its the current way of doing it.

**Comment by vishwanathovi** [comment]
@kamranahmedse Is this a required feature? If yes, I can look into it.
