### ISSUE TITLE
Can the highlighted area button be disabled?

### ISSUE THREAD

**Issue by codeManage** [kamranahmedse/driver.js#171]
Can the highlighted area button be disabled?

**Comment by vmangelovv** [comment]
you can onNext the previous element and set the button css 'pointer-events: none'

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. It now applies `driver-active-element` to the highlighted element which you can use instead in CSS.

```css
.driver-active-element {
  pointer-events: 'none'
}
```

Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
