### ISSUE TITLE
Why does the close button trigger reset?

### ISSUE THREAD

**Issue by jjjjyx** [kamranahmedse/driver.js#172]
https://github.com/kamranahmedse/driver.js/blob/49f9e85157c2972fde906748aedf58861cc1482b/src/index.js#L141-L146

What should I do if I want to listen or catch a shutdown event?

**Comment by kamranahmedse** [comment]
Close button triggers the reset because it is "shutting down" the driver. 
If you want to hook into that, you have the `onReset` callback in the for [options](https://github.com/kamranahmedse/driver.js#driver-definition) for that
