### ISSUE TITLE
[Feature request] Define padding for each popover

### ISSUE THREAD

**Issue by cuzi** [kamranahmedse/driver.js#174]
Currently, to define different padding for a popover highlight is on the init of the Driver and can't be different between the element.
I want to add padding only for some of the elements in the same Drive start
for example (my case) for span elements (texts) I want to set padding to 10
for Buttons i want to set padding 10

Please tell me if it is possible (I can even make a PR by my own if needed)

**Comment by cuzi** [comment]
Currently, to define different padding for a popover highlight is on the init of the Driver and can't be different between the element.
I want to add padding only for some of the elements in the same Drive start
for example (my case) for span elements (texts) I want to set padding to 10
for Buttons i want to set padding 10

Please tell me if it is possible (I can even make a PR by my own if needed)

**Comment by kamranahmedse** [comment]
We now have a `stagePadding` configuration option for this.

Also, we just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
