### ISSUE TITLE
Is there any way to set the background of highlighted element?

### ISSUE THREAD

**Issue by dingyaguang117** [kamranahmedse/driver.js#179]
I want to change the background of the highlighted element.
I can do that this way. (e.g. remove it )

```
#driver-highlighted-element-stage {
  background-color: rgba(0,0,0,0) !important;
}

```

but for some elements, I need white background,  So I have to restore it like this:

```
function restoreBackground() {
  let element = document.querySelector('#driver-highlighted-element-stage')
  let style = element.getAttribute('style')
  element.setAttribute('style', style + '; background-color: white !important')
}


onHighlighted() {
     restoreBackground()
}
```
It's really ugly.

Is there any way to set the background of highlighted elements at each step?

**Comment by kamranahmedse** [comment]
You can do that by [assigning class names to relevant popups](https://github.com/kamranahmedse/driver.js#driver-definition)

**Comment by kapooramit** [comment]
@kamranahmedse : But the class names are assigned only to popups and not to the selected element. Isn't that right? Maybe I am missing something?

**Comment by zhangwen9229** [comment]
I have the same question?
