### ISSUE TITLE
Tour does not start if the second element is hidden

### ISSUE THREAD

**Issue by kapooramit** [kamranahmedse/driver.js#182]
I believe this has something to do with https://github.com/kamranahmedse/driver.js/issues/25 but not sure. My second element #sidebar is collapsible. When I collapse it and I try to start thr tour - it doesn't start. If I display it again, the tour starts working! 

```
//Defines driver for all calls
const driver = new Driver({
  className: 'scoped-class',        // className to wrap driver.js popover
  animate: false,                    // Whether to animate or not
  opacity: 0.75,                    // Background opacity (0 means only popovers and without overlay)
  padding: 10,                      // Distance of element from around the edges
  allowClose: false,                 // Whether the click on overlay should close or not
  overlayClickNext: false,          // Whether the click on overlay should move next
  doneBtnText: 'Done',              // Text on the final button
  closeBtnText: 'Close',            // Text on the close button for this step
  stageBackground: '#ffffff',       // Background color for the staged behind highlighted element
  nextBtnText: 'Next →',              // Next button text for this step
  prevBtnText: '← Previous',          // Previous button text for this step
  showButtons: true,               // Do not show control buttons in footer
  keyboardControl: true,            // Allow controlling through keyboard (escape to close, arrow keys to move)
  scrollIntoViewOptions: {block:"top"},        // We use `scrollIntoView()` when possible, pass here the options for it if you want any
  onHighlightStarted: (Element) => {}, // Called when element is about to be highlighted
  onHighlighted: (Element) => {},      // Called when element is fully highlighted
  onDeselected: (Element) => {},       // Called when element has been deselected
  onReset: (Element) => {},            // Called when overlay is about to be cleared
  onNext: (Element) => {},                    // Called when moving to next step on any step
  onPrevious: (Element) => {},                // Called when moving to previous step on any step
});
 
//Start listening for click on the on the tour button and move forward when it happens. 
document.getElementById('launchtour')
        .addEventListener('click', function(event) {
          event.stopPropagation();

// Define the tour steps if the button is clicked. 
driver.defineSteps([
  {
    element: '#launchtour',
    popover: {
      title: 'Welcome to the Online Help Tour!',
      description: 'Watch this tour...',
      position: 'left',
    nextBtnText: 'okay, Start!'	
    }
  },
  {
    element: '#sidebar',
    popover: {
      title: 'Access the Tree',
      description: 'Browse the complete docs...',
      position: 'right'     
    }
  },
  {
    element: '#pdf_button',
    popover: {
      title: 'Create PDFs',
      description: 'Create PDFs ...',
      position: 'left'
    }
  },
  {
    element: '#selectglobe',
    popover: {
      title: 'Switch ',
      description: 'Select any of the ...',
      position: 'left'
    }
  },
  ]);

// Launch the tour if the button is clicked. 
driver.start();

});
```

**Comment by kapooramit** [comment]
@kamranahmedse : I am stuck with this element and code below: 
```
onHighlightStarted: (Element) => {
if ((Element.visibility === "hidden")) {driver.next(); }
 }, // Called when element is about to be highlighted
```
The above code works if the element is not in the DOM. However, if the element is there but with CSS display:none or CSS visibility:hidden, the code doesn't work. In the case above, the tour doesn't even start. 

What else do I need to do or change?

**Comment by kapooramit** [comment]
@kamranahmedse : Did you get a chance to look at this?

**Comment by Danyx1980** [comment]
@kapooramit have you had any success with this? I'm trying the following code: 

```
                if (element["node"]["offsetParent"] == null) {
                    if (this.driver.hasNextStep())
                        this.driver.moveNext();
                    else
                        this.driver.reset();
                }
```

But moveNext doesn't actually progress to the next step.

**Comment by vitorleonel** [comment]
I had a similar problem, where the solution was to mount the tour checking before if the element exists, then add it to the array of steps.

That is, in the tour will only be the element that exists in the DOM. Does it help you in any way?

**Comment by larissamasson** [comment]
I tried to use it - and and it didn't work:

```
onHighlightStarted: (Element) => {
        if (!$(Element.getNode()).is(':visible')) {
          if(driver.hasNextStep()){
            driver.moveNext();
          }
        }
      }
```

I tested `moveNext() `alone and it works fine, and I tested `onHighlightStarted` witih `if (!$(Element.getNode()).is(':visible'))` an it works fine to, but together it generates an infinite looping = (

**Comment by zhicong** [comment]
This worked for me, but as @larissamasson pointed out, it results in an infinite loop because in onHighlightStarted, `moveNext()` unfortunately points to the step that is about to be highlighted. The library currently doesn't have an option to skip 2 steps ahead either.

You can still call driver.reset() to end the tour if you hit a hidden element though.

> @kapooramit have you had any success with this? I'm trying the following code:
> 
> ```
>                 if (element["node"]["offsetParent"] == null) {
>                     if (this.driver.hasNextStep())
>                         this.driver.moveNext();
>                     else
>                         this.driver.reset();
>                 }
> ```
> 
> But moveNext doesn't actually progress to the next step.

**Comment by deepika231-max** [comment]
> @kamranahmedse : I am stuck with this element and code below:
> 
> ```
> onHighlightStarted: (Element) => {
> if ((Element.visibility === "hidden")) {driver.next(); }
>  }, // Called when element is about to be highlighted
> ```
> 
> The above code works if the element is not in the DOM. However, if the element is there but with CSS display:none or CSS visibility:hidden, the code doesn't work. In the case above, the tour doesn't even start.
> 
> What else do I need to do or change?

Hi @kapooramit ,
I want to use this code as my element is not in the DOM. But it doesn't works for me.
![Screenshot from 2020-04-20 17-02-03](https://user-images.githubusercontent.com/60771969/79747321-12c4b300-8329-11ea-8282-c1247887455e.png)

**Comment by kapooramit** [comment]
I did this to workaround the issue and it works now:
`onHighlightStarted: (Element) => { 
    								if ((Element.visibility === "hidden")) {
                                      driver.next();		//Skip the next element to be highlighted if it is not in the DOM
                                    }
                                   }, // Called when element is about to be highlighted`

**Comment by kapooramit** [comment]
This is not the best solution but it just needs user to click or press Next once more to move the available element.
