### ISSUE TITLE
driver.js not working in angular 7

### ISSUE THREAD

**Issue by amit112** [kamranahmedse/driver.js#186]
all the code  are added in angular component  as per documentation :

import * as Driver from 'driver.js';
import 'driver.js/dist/driver.min.css';
----------------
        const steps = [
            {
                element: '#gsSelect',
                popover: {
                    className: 'first-step-popover-class',
                    title: 'Title on Popover',
                    description: 'Body of the popover',
                    position: 'right'
                }
            },
            // {
            //     element: this.htmlDoc.getElementById('rateType'),
            //     popover: {
            //         title: 'Title on Popover',
            //         description: 'Body of the popover',
            //         position: 'top'
            //     }
            // },
            // {
            //     element: this.htmlDoc.getElementById('childGroup'),
            //     popover: {
            //         title: 'Title on Popover',
            //         description: 'Body of the popover',
            //         position: 'right'
            //     }
            // }
        ];
 
        this.driver.defineSteps(steps);
        // Start the introduction

        
        this.driver.start();

**Comment by amit112** [comment]
I have solved  this issue as per following snippet . Calling these methods in any other angular life cycle  hooks would not have worked except  ngAfterViewChecked hook  :  
ngAfterViewChecked(): any {
       const driver = new Driver({opacity: 0});
        const steps = [
            {
                element: '#firstv',
                popover: {
                  className: 'first-step-popover-class',
                  title: 'Title on Popover',
                  description: 'Body of the popover',
                  position: 'bottom'
            
                }
              }
        ];
        driver.defineSteps(steps);
        driver.start();
    }

**Comment by sefatanam** [comment]
not working in angular 11, it just give a black bip screen for a second
