### ISSUE TITLE
how to prevent popup from closing when you click outside

### ISSUE THREAD

**Issue by amit112** [kamranahmedse/driver.js#187]

**Comment by kamranahmedse** [comment]
You can use `allowClose` [option](https://github.com/kamranahmedse/driver.js#driver-definition) for that

**Comment by ercantomac** [comment]
> You can use `allowClose` [option](https://github.com/kamranahmedse/driver.js#driver-definition) for that

Setting that option to false also hides the close button. Is there a way to keep the close button?

**Comment by altai861** [comment]
Yeah what to do about it when close button disappears when allowClose option is set to false, I want to keep the close button while closing the tour when clicked outside.

**Comment by Ananth0005** [comment]
onPopoverRender: (popover) => {
                const closeBtn = popover.wrapper.querySelector('.driver-popover-close-btn');
                if (closeBtn) {
                    closeBtn.style.display = 'inline-block';
                }
            },

this worked for me
