### ISSUE TITLE
how to highlight complete dropdrown in steps

### ISSUE THREAD

**Issue by amit112** [kamranahmedse/driver.js#188]

**Comment by kamranahmedse** [comment]
Please provide a [codesandbox](https://codesandbox.io) example

**Comment by amit112** [comment]
<div class="mb-8">
                <select  matNativeControl  id="ddlGS" placeholder="Goods/Services"    [ngClass]="ddlGS === 1 ? 'optBgClrCoral'  : 'optBgClrAqua'"     class="dropdown-sizing-small" (selectionChange)="ddlGSChange()" [(ngModel)]="ddlGS" name="ddlGS">
                  <option  [value]=1 >Goods</option>
                  <option  [value]=2>Services</option>
                </select>
                <mat-select placeholder="Parent Group" id="ddlPG"   class="dropdown-sizing" [(formControl)]="selectedRatTypes"
                (selectionChange)="onRatTypeChange()" name="Parent Group" multiple>
                <mat-select-trigger>
                    {{selectedRatTypes.value ? selectedRatTypes.value[0] : ''}}
                    <span *ngIf="selectedRatTypes.value?.length > 1" class="example-additional-selection">
                        (+{{selectedRatTypes.value.length - 1}}
                        {{selectedRatTypes.value?.length === 2 ? 'other' : 'others'}})
                    </span>
                </mat-select-trigger>
                <mat-option>
                    <ngx-mat-select-search [formControl]="ratTypeFilterCtrl"  [placeholderLabel]="'Find Parent Group...'"
                        [noEntriesFoundLabel]="'no matching result found'"></ngx-mat-select-search>
                </mat-option>
                <mat-divider style="margin-top: 12px"></mat-divider>  
                <mat-option (onSelectionChange)="selectAllRatType($event)" [value]="0">--Select All--
                </mat-option>
                <mat-divider></mat-divider>    
                <mat-option *ngFor="let item of ratTypeFiltered | async" [value]="item.id1">
                    {{item.str|numberPadding:item.id1}}
                </mat-option>
            </mat-select>
            <mat-select placeholder="Child Group"  class="dropdown-sizing" [(formControl)]="selectedCgIDs"
                (selectionChange)="onCgIDChange()" name="Child Group" multiple>
                <mat-select-trigger>
                    {{selectedCgIDs.value ? selectedCgIDs.value[0] : ''}}
                    <span *ngIf="selectedCgIDs.value?.length > 1" class="example-additional-selection">
                        (+{{selectedCgIDs.value.length - 1}}
                        {{selectedCgIDs.value?.length === 2 ? 'other' : 'others'}})
                    </span>
                </mat-select-trigger>
                <mat-option>
                    <ngx-mat-select-search [formControl]="cgIdsFilterCtrl" [placeholderLabel]="'Find  Child Group...'"
                        [noEntriesFoundLabel]="'no matching result found'"></ngx-mat-select-search>
                </mat-option>
                <mat-divider style="margin-top: 12px"></mat-divider>
                <mat-option (onSelectionChange)="selectAllCgIds($event)" [value]="0">--Select All--
                </mat-option>
                <mat-divider></mat-divider>
                <mat-option *ngFor="let item of cgIdsFiltered | async" [value]="item.id1"> {{item.str|numberPadding:item.id1}}
                </mat-option>
            </mat-select>
            <mat-select placeholder="Module"  class="dropdown-sizing-small" [(formControl)]="selectedModules"
                (selectionChange)="onModuleChange()" name="Module" multiple>
                <mat-select-trigger>
                    {{selectedModules.value ? selectedModules.value[0] : ''}}
                    <span *ngIf="selectedModules.value?.length > 1" class="example-additional-selection">
                        (+{{selectedModules.value.length - 1}}
                        {{selectedModules.value?.length === 2 ? 'other' : 'others'}})
                    </span>
                </mat-select-trigger>
                <mat-option>
                    <ngx-mat-select-search [formControl]="modulesFilterCtrl" [placeholderLabel]="'Find Module...'"
                        [noEntriesFoundLabel]="'no matching result found'"></ngx-mat-select-search>
                </mat-option>
                <mat-divider style="margin-top: 12px"></mat-divider>
                <mat-option (onSelectionChange)="selectAllModules($event)" [value]="0">--Select All--
                </mat-option>
                <mat-divider></mat-divider>
                <mat-option *ngFor="let item of modulesFiltered | async" [value]="item.id1">
                    {{item.str|numberPadding:item.id1}}
                </mat-option>
            </mat-select>
        <input matInput placeholder="Enter Request Ref(max 100 chars)" id="txtRR"   class="txtRRefBox" [(ngModel)]="requestRef" name="requestRef">
        <mat-select placeholder="Department" class="dropdown-sizing-md" id="ddlDept" [(ngModel)]="deptID" name="deptID">
            <mat-option [value]=null>--Select Department--
            </mat-option>
            <mat-option *ngFor="let item of departments"  [value]="item.DepartmentUId">
                {{item.DepartmentName|numberPadding:item.DepartmentUId}}
            </mat-option>
        </mat-select>
        <button mat-raised-button class="mr-8" color="accent"  id="btnReq"  (click)="OpenPopup()">Raise Request</button>
    </div>

**Comment by amit112** [comment]
I have applied tour over mat-select but when dropdown open options not highlighting
