### ISSUE TITLE
driver.js not showing popover in angular8

### ISSUE THREAD

**Issue by muqeed11** [kamranahmedse/driver.js#193]
`import` * `as Driver from 'driver.js';`
`import 'driver.js/dist/driver.min.css';`

driver = new Driver();

const steps = [
            {
                element: '#apiheader',
                popover: {
                     className: 'first-step-popover-class',
                    title: 'API header',
                    description: 'API header',
                    position: 'right'
                }
            },
            {
                element: '#newapi',
                popover: {
                    title: 'Title on Popover',
                    description: 'Body of the popover',
                    position: 'top'
                }
            },
        ];
        this.driver.defineSteps(steps);
        this.driver.start();`

Above code is showing only white color on the item.

**Comment by kamranahmedse** [comment]
Could you please provide a sample example on [codesandbox](https://codesandbox.io)?

**Comment by kamranahmedse** [comment]
Closing it for no response
