### ISSUE TITLE
Taps are doubled on touch screen device

### ISSUE THREAD

**Issue by rengaw** [kamranahmedse/driver.js#195]
We are using the driver.js library in Chromium (actually Electron) on Windows touchscreen devices. It works fine when using a mouse to click on the forward and backward buttons, but when tapping on screen using your finger, the actions seem to be doubled. Steps in are skipped, indicating the actions are firing twice. I think the problem is that when the touch events are available, event handlers are registered for *both* the the touchstart and click events. I believe an "else" is needed when these event handlers are bound, i.e.,

    if (!('ontouchstart' in document.documentElement)) {
      this.window.addEventListener('click', this.onClick, false);
    } else {
      this.window.addEventListener('touchstart', this.onClick, false);
    }

This would replace the code starting on line 98 of index.js. This change seemed to help me.

Mike

**Comment by kamranahmedse** [comment]
Fixed in `0.9.8` – Thank you for reporting.
