### ISSUE TITLE
Package description misleading

### ISSUE THREAD

**Issue by bm-stschneider** [kamranahmedse/driver.js#198]
https://bundlephobia.com/result?p=driver.js@0.9.8
it looks more like 4Xkb instead of 4.x kb
![image](https://user-images.githubusercontent.com/30625381/66647281-c46f8280-ec28-11e9-92ba-b1d8454688c3.png)

**Comment by kamranahmedse** [comment]
It was the min+gzip size last I checked and it looks like it has increased to 12kb. I will look at the bundle to see if it can be improved somehow. However, I have updated the readme. Thank you!
