### ISSUE TITLE
Popovers is not matching the focused element

### ISSUE THREAD

**Issue by aloupfor** [kamranahmedse/driver.js#20]
I tried the demo page and was able to trigger popovers that don't match the focused element.

I started with "With Animation" then switched to "without Animation" when it was available with popover "Lets talk features".

![popovers-out-of-focus](https://user-images.githubusercontent.com/11750180/37411763-d6786d0c-27a3-11e8-8d2e-73cc12f890f5.gif)

I think it is good to let you know this.

**Comment by kamranahmedse** [comment]
Ahh yes, I noticed that earlier today. You can't trigger two Drivers at the same time, it gets messed up. Should be quick fix, I will check tonight. Thanks for reporting.

**Comment by kamranahmedse** [comment]
Thank you for reporting. It has been fixed. Demo will be deployed soon.

@moghya no, that would be a mess. Also, it is something that app should be responsible of handling not the plugin. For now, I have updated the demo to reset the existing driver and run the new one.
