### ISSUE TITLE
[Feature Request] Make "title" optional

### ISSUE THREAD

**Issue by scrobbleme** [kamranahmedse/driver.js#203]
Seems like title is required, when a description is set.

It would be nice to be able to skip the title and only use the description instead.

**Comment by ChipDenton** [comment]
It already does this, but it's just not very intuitive. 

You still technically have to set the title but if you set it to a space, " ", then the description will appear but the title won't and it doesn't even leave a space for it (height is 0). (Note: setting it to an empty string "" seems to just make the popover not appear so make sure you put a space inside)

Do this:
`popover: {
  title: " ",
  description: "This is a description",
},`
![this is a description](https://user-images.githubusercontent.com/50883471/73557994-e713ea00-4417-11ea-9184-6c451c1d66f9.png)

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. Title is optional now. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
