### ISSUE TITLE
Examples lower down demo page don't work

### ISSUE THREAD

**Issue by angusf** [kamranahmedse/driver.js#21]
I'm sure this is just an issue for me on my office network & machine - but makes it hard for me to advocate to non-technical team that we could use this.

 GET https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/monokai.min.css net::ERR_INSECURE_RESPONSE
driver:359 GET https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js net::ERR_INSECURE_RESPONSE
2buttons.js:1 [Violation] Avoid using document.write().
C @ buttons.js:1
L @ buttons.js:1
e @ buttons.js:1
l @ buttons.js:1
driver-demo.js:120 Uncaught ReferenceError: hljs is not defined
    at driver-demo.js:120
    at NodeList.forEach (<anonymous>)
    at HTMLDocument.<anonymous> (driver-demo.js:119)
(anonymous) @ driver-demo.js:120
(anonymous) @ driver-demo.js:119
widgets.js:1 GET https://platform.twitter.com/js/button.556f0ea0e4da4e66cfdc182016dbd6db.js net::ERR_INSECURE_RESPONSE
Function.bind.test.window.__twttr.window.__twttr.widgets.window.__twttr.widgets.init.e.e @ widgets.js:1
r @ widgets.js:10
i.initialize @ widgets.js:8
(anonymous) @ widgets.js:8
(anonymous) @ widgets.js:8
o @ widgets.js:8
i @ widgets.js:8
r._flush @ widgets.js:8
(anonymous) @ widgets.js:8
p @ widgets.js:8
characterData (async)
(anonymous) @ widgets.js:8
K @ widgets.js:8
r.add @ widgets.js:8
o @ widgets.js:8
(anonymous) @ widgets.js:8
o @ widgets.js:8
s @ widgets.js:8
(anonymous) @ widgets.js:1
r @ widgets.js:11
o @ widgets.js:11
syndication.twitter.com/i/jot?l=%7B%22widget_origin%22%3A%22http%3A%2F%2Fkamranahmed.info%2Fdriver%23%22%2C%22widget_frame%22%3Anull%2C%22duration_ms%22%3A23.55999999999983%2C%22_category_%22%3A%22tfw_client_event%22%2C%22triggered_on%22%3A1521062763757%2C%22dnt%22%3Afalse%2C%22client_version%22%3A%22c419f42%3A1520970215484%22%2C%22format_version%22%3A1%2C%22event_namespace%22%3A%7B%22client%22%3A%22tfw%22%2C%22action%22%3A%22render%22%2C%22page%22%3A%22page%22%2C%22component%22%3A%22performance%22%7D%7D:1 GET https://syndication.twitter.com/i/jot?l=%7B%22widget_origin%22%3A%22http%3A%2F%2Fkamranahmed.info%2Fdriver%23%22%2C%22widget_frame%22%3Anull%2C%22duration_ms%22%3A23.55999999999983%2C%22_category_%22%3A%22tfw_client_event%22%2C%22triggered_on%22%3A1521062763757%2C%22dnt%22%3Afalse%2C%22client_version%22%3A%22c419f42%3A1520970215484%22%2C%22format_version%22%3A1%2C%22event_namespace%22%3A%7B%22client%22%3A%22tfw%22%2C%22action%22%3A%22render%22%2C%22page%22%3A%22page%22%2C%22component%22%3A%22performance%22%7D%7D net::ERR_INSECURE_RESPONSE
Image (async)
l @ widgets.js:9
s @ widgets.js:9
i @ widgets.js:9
(anonymous) @ widgets.js:8
r @ widgets.js:8
o @ widgets.js:8
r._flush @ widgets.js:9
(anonymous) @ widgets.js:8
setTimeout (async)
r._scheduleFlush @ widgets.js:9
r.add @ widgets.js:9
s @ widgets.js:8
t.exports @ widgets.js:11
(anonymous) @ widgets.js:11
(anonymous) @ widgets.js:8
(anonymous) @ widgets.js:8
setTimeout (async)
d @ widgets.js:8
(anonymous) @ widgets.js:8
trigger @ widgets.js:8
(anonymous) @ widgets.js:8
Promise resolved (async)
o @ widgets.js:8
s @ widgets.js:8
(anonymous) @ widgets.js:1
r @ widgets.js:11
o @ widgets.js:11
driver:368 GET https://www.google-analytics.com/analytics.js net::ERR_INSECURE_RESPONSE
(anonymous) @ driver:368
(anonymous) @ driver:369
VM129 buttons.js:1 GET https://api.github.com/repos/kamranahmedse/driver.js net::ERR_INSECURE_RESPONSE
V @ VM129 buttons.js:1
m @ VM129 buttons.js:1
M @ VM129 buttons.js:1
(anonymous) @ VM129 buttons.js:1
(anonymous) @ VM129 buttons.js:1
VM131 buttons.js:1 GET https://api.github.com/users/kamranahmedse net::ERR_INSECURE_RESPONSE
V @ VM131 buttons.js:1
m @ VM131 buttons.js:1
M @ VM131 buttons.js:1
(anonymous) @ VM131 buttons.js:1
(anonymous) @ VM131 buttons.js:1
buttons.js:1 GET https://api.github.com/repos/kamranahmedse/driver.js net::ERR_INSECURE_RESPONSE
V @ buttons.js:1
m @ buttons.js:1
M @ buttons.js:1
(anonymous) @ buttons.js:1
(anonymous) @ buttons.js:1
buttons.js:1 GET https://api.github.com/users/kamranahmedse net::ERR_INSECURE_RESPONSE
V @ buttons.js:1
m @ buttons.js:1
M @ buttons.js:1
(anonymous) @ buttons.js:1
(anonymous) @ buttons.js:1

**Comment by kamranahmedse** [comment]
Hey, what browser is this?

**Comment by kamranahmedse** [comment]
It should be fine now, there were a few issues on the demo page because of which it wasn't working in IE. Thanks
