### ISSUE TITLE
Issue on focus for the highlight element

### ISSUE THREAD

**Issue by rcogal** [kamranahmedse/driver.js#217]
![image](https://user-images.githubusercontent.com/29474267/73810887-d6e27d00-4812-11ea-89d6-1fb64a4f4bfd.png)

Div container has scroll and when trying to start the driver of defined steps, it redirects to correct position but when scrolling the div container, the focus is not correct because the highlight container  is moving instead of fixed position

**Comment by rcogal** [comment]
Same on this one
![image](https://user-images.githubusercontent.com/29474267/73811909-d1d2fd00-4815-11ea-928a-f97648564400.png)

**Comment by tomaszn** [comment]
This would be a useful feature!
Could be achieved by adding a `focus: '<css_selector>'` in the step definition.
Additionally, `focus: null` could be used to remove focus.

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
