### ISSUE TITLE
Is there a way to execute a non driver.js function when the Done button is clicked in a tour?

### ISSUE THREAD

**Issue by FaramarzPDA** [kamranahmedse/driver.js#218]
I need to do more and execute other functions on the page when the "Done" button is clicked on the last pop-over Tour. I added a className to the last pop-over, I thought that helps to find and target the Done button on the last pop-over but it doesn't look all steps are available in DOM when the page is loaded.

**Comment by kamranahmedse** [comment]
You can do that using `onReset`

**Comment by FaramarzPDA** [comment]
Thanks, did you mean something like this?

```
element: '#masonry-drop-down',
	popover: {
    	className: 'last-step-popover',
		title: 'Filter',
      	description: 'This is how you can filter the news by Category.',
      	position: 'right'
    },
	onReset: () => {
		console.log('closed now');
	}
```
I tried this and it didn't do anything for me.

**Comment by FaramarzPDA** [comment]
Never mind, I think I called it in a wrong location, this worked for me:

```
const driver = new Driver({
	onReset: () => {
		console.log('closed now');
	}
});
```
