### ISSUE TITLE
How does Driver.js still work when I switch to another "url"

### ISSUE THREAD

**Issue by JazudyZura** [kamranahmedse/driver.js#219]
How Driver.js still works when I switch to another "url". The website has many pages, when I moved the page it was broken.

![bugDriverjs](https://user-images.githubusercontent.com/44596375/74522960-cc309200-4f4e-11ea-8f1e-cc63de8a719f.png)

**Comment by kamranahmedse** [comment]
This has to be handled in your application logic. Wait for the page to load and trigger the driver when the page has been loaded.
