### ISSUE TITLE
How to use with React

### ISSUE THREAD

**Issue by amiiy** [kamranahmedse/driver.js#22]
Thanks for awesome work!
how can use driver.js inside react components?
can someone provide simple code to show use case with react?

**Comment by kamranahmedse** [comment]
Hey, you would use it like any other library

```javascript
// Import the required JavaScript and CSS on top of the component
import * as Driver from 'driver.js';
import 'driver.js/dist/driver.min.css';

// then add a click handler or however you
// might want to trigger it and initialize the Driver
const driver = new Driver();
driver.highlight({
    element: '#title-item',
    stageBackground: 'blue'
});
```

**Comment by eugenelavr** [comment]
> import 'driver.js/dist/driver.min.css';

But how it applies to the drivers DOM nodes? Does it need some specific webpack setup?

**Comment by makeupsomething** [comment]
Is this also valid for using with vue? I get a error like when i copy this example.
```
Dashboard.vue?84d9:35 Uncaught TypeError: Driver is not a constructor
```

**Comment by jmderueda** [comment]
Example is not working

**Comment by jmderueda** [comment]
Ok, guys some clarity over this... Just try to create the new instance on componentDidMount(), I was using it on the render and it was not working for obvious reasons!

**Comment by Attrash-Islam** [comment]
Yeah. You should import and run in didMount if you do Server Side Rendering

**Comment by NatashaKSS** [comment]
Yup, and if you were using React hooks, the equivalent of `componentDidMount` would be a `useEffect` hook like this:

```javascript
useEffect(() => {
  // Run Driver on component mount
  const driver = new Driver();
  driver.highlight({
    element: '#title-item',
    stageBackground: 'blue'
  });
}, []);
```
The empty list in the 2nd argument of `useEffect` is meant to ensure that the callback is executed only on the first render.

**Comment by fadilnatakusumah** [comment]
why can't we use jsx inside the `description` attribute? is there any workaround?

**Comment by chrisk-7777** [comment]
> why can't we use jsx inside the `description` attribute? is there any workaround?

"why" - I would say because DriveJS isn't part of the React DOM. React won't attempt to render JSX arbitrarily located somewhere in your project. 

You can easily use JSX to create HTML strings though, but to be clear, it still won't be part of "React", and you won't be able to attach React events like `onClick`

```jsx
import { renderToString } from 'react-dom/server';

// in steps:

{
  description: renderToString(
    <div>
      hello<strong>world!</strong>
    </div>
  ),
  ...
}
```

**Comment by Wfelipe2011** [comment]
Recentemente, ao tentar implementar tours em diferentes componentes, me deparei com um problema inesperado de vazamento de tours para outras partes da página.

Para resolver esse problema, fiz uma pequena alteração na forma como o código era executado. Em vez de declarar o driver no início do componente, encapsulei a execução dentro de uma função. 

Isso não só resolveu o problema de vazamento dos tours para outros componentes, mas também ajudou a manter a execução do tour restrita ao componente específico em que estava sendo utilizado.

```tsx
//...restante do seu código...
const driverAction = () => {
  const driverObj = driver({
    showProgress: true,
    steps: [
      { element: '#publisher-gps', popover: { title: 'GPS', description: 'Clique aqui para abrir o GPS e ser direcionado para a localização da quadra.' } },
      { element: '#publisher-details', popover: { title: 'Detalhes', description: 'Visualize os detalhes do endereço e marque as casas nesta seção.' } },
    ],
    nextBtnText: 'Próximo',
    prevBtnText: 'Anterior',
    doneBtnText: 'Finalizar',
    progressText: '{{current}} de {{total}}',
  });
  driverObj.drive()
}

return (
  <RootModeScreen mode={isLoading}>
    <HelpCircle onClick={driverAction} size={50} fill="rgb(121 173 87 / 1)" className='text-gray-50 z-10 cursor-pointer fixed bottom-0 right-0 m-4' />
    {/* ...restante do seu código... */}
  </RootModeScreen>
);
```

Espero que essa solução possa ser útil para quem estiver lidando com problemas semelhantes ao integrar a biblioteca driver.js em aplicativos React.

Se você tiver alguma dúvida ou sugestão sobre como melhorar ainda mais essa abordagem, fique à vontade para compartilhar nos comentários.

**Comment by utsavPatidar9316** [comment]
npm install driver.js
import "driver.js/dist/driver.css";
import { driver } from "driver.js";
useEffect(() => {
    startTour();
  }, []);// adjust the show of drive the preview as dependency 
![Uploading Screenshot (30).png…]()


  const startTour = () => {
    const config = {
      steps: [
        {
          element: "#searchUser",
          popover: {
            title: "Step 1",
            description: "This is the first step of the tour.",
          },
        },
        // Add more steps as needed
      ],
      allowClose: true,
      // Add other configuration options as needed
    };

    const tourInstance = driver(config);

    // Start the tour directly
    tourInstance.drive();
  };

**Comment by bigTig** [comment]
Hi，Man，why I  import 'driver.js/dist/driver.css' in React tsx，It throw some error to me.
![image](https://github.com/kamranahmedse/driver.js/assets/80088198/fdf16ab4-dcb1-4a14-891b-b0583b960afe)
who can help me, 
`
import { driver } from 'driver.js'
import 'driver.js/dist/driver.css'

const driverObj = driver({
    showProgress: true,
    steps: [
      {
        element: '.left-logo',
        popover: { title: 'GitHub仓库', description: '喜欢就给Star🌟吧！' },
      },
      { element: '.logo', popover: { title: '欢迎回来', description: '我是程序猿阿峰' } },
      { element: '.username', popover: { title: '用户名', description: '可以使用 admin' } },
      { element: '.password', popover: { title: '密码', description: '可以使用 admin123' } },
      {
        element: '.agreement',
        popover: { title: '阅读协议', description: '记得勾选哦' },
      },
      {
        element: '.login-form-button',
        popover: { title: '点我吧', description: '点我就可以登录啦' },
      },
    ],
  })

  useLayoutEffect(() => {
    driverObj.drive()
  }, [driverObj])
`

**Comment by guifeliper** [comment]
> Recentemente, ao tent
Hey @Wfelipe2011, your comment is pretty helpful sadly you wrote in Portuguese instead of English. It is common to always talk in English in this type of repo. 


E ai @Wfelipe2011 , seu comentário é bastante útil, infelizmente você escreveu em Portugues ao invés de Inglês. É comum escrever em Ingles nesses tipos de repositorios. Foi por isso que tu recebeu alguns downvotes, mas obrigado pela contribuição.

**Comment by khannoussi-malek** [comment]
Solution for Integrating Driver.js in React
I encountered a challenge integrating Driver.js with React and found a solution that I’d like to share. Here's how you can handle Driver.js steps and manage their state using React context and local storage.

1. Create a Driver Context
Define a context to manage Driver.js steps:
```TS
import React, { FC, PropsWithChildren, createContext, useContext, useState, useEffect, useCallback } from 'react';
import { DriveStep, driver as Driver } from 'driver.js';
import { isBrowser } from 'framer-motion';
import { useLocalStorage } from '@/hooks/useLocalStorage';

interface DriverContextProps {
  addStep: (step: DriveStep[]) => void;
}

const DriverContext = createContext<DriverContextProps>({
  addStep: (step: DriveStep[]) => {},
});

export const useDriver = () => useContext(DriverContext);

export const DriverProvider: FC<PropsWithChildren<unknown>> = ({ children }) => {
  const [steps, setSteps] = useState<DriveStep[]>([]);
  const [realyOldSteps, setRealyOldSteps] = useLocalStorage('driverSteps', []);
  const [oldSteps, setOldSteps] = useState<string[]>(realyOldSteps);

  useEffect(() => {
    setRealyOldSteps(oldSteps);
  }, [oldSteps, setRealyOldSteps]);

  const addStep = async (steps: DriveStep[]) => {
    if (isBrowser) {
      steps = steps.filter(
        (step) => oldSteps.indexOf(`${step.element}`) === -1
      );
      setSteps((prevSteps) =>
        [...prevSteps, ...steps].filter(
          (step) => oldSteps.indexOf(`${step.element}`) === -1
        )
      );
      setOldSteps((old) => [...old, ...steps.map((step) => `${step.element}`)]);

      startTour();
    }
  };

  const startTour = useCallback(() => {
    const driver = Driver({
      showProgress: true,
      steps,
    });
    driver.drive();
  }, [steps]);

  useEffect(() => {
    startTour();
  }, [startTour, steps]);

  useEffect(() => {
    return () => {
      setSteps([]);
    };
  }, []);

  return (
    <DriverContext.Provider value={{ addStep }}>
      {children}
    </DriverContext.Provider>
  );
};
```
2. Create a Custom Hook for Local Storage
Here's a custom hook to manage local storage:
```ts
import { useState } from 'react';

export const useLocalStorage = (key: string, initialValue: any) => {
  const initial = () => {
    if (typeof window !== 'undefined') {
      const item = localStorage.getItem(key);
      return item ? JSON.parse(item) : initialValue;
    }
    return initialValue;
  };

  const [value, setValue] = useState(initial);

  const removeValue = () => {
    if (typeof window !== 'undefined') {
      localStorage.removeItem(key);
      setValue(initialValue);
    }
  };

  const updateValue = (newValue: any) => {
    if (typeof window !== 'undefined') {
      localStorage.setItem(key, JSON.stringify(newValue));
      setValue(newValue);
    }
  };
  return [value, updateValue, removeValue];
};
```
3. Usage
Wrap your application with DriverProvider and use the useDriver hook to add steps:
```ts
const { addStep } = useDriver();

React.useEffect(() => {
  addStep([
    {
      element: '#darkMode',
      popover: {
        title: 'Connect With Me',
        description: '🌐 Explore more on my social media channels. Click the buttons to connect!',
      },
    },
  ]);
}, []);
```
This setup should help in managing Driver.js tours effectively in your React app.

Testing
I’ve tested this setup on my portfolio website, which you can view [here](https://www.malekkhannoussi.tn/). This integration manages Driver.js tours effectively and ensures steps are shown as intended

**Comment by solarpush** [comment]
@khannoussi-malek 
Thanks you for your tips i have start from you code and add other behavior, to deduplicate and manage in multiples tabs and locations.
I post here when it's done thanks you.
