### ISSUE TITLE
Driver.js Invisble Element on Driver Start

### ISSUE THREAD

**Issue by GoChartingAdmin** [kamranahmedse/driver.js#220]
Hi,

I am facing two issues as can be seen in the below video
1. The main element to be highlighted gets hidden
2. Scrollbar appears on highlighting elements to the far right

![BTCUSD_ 9954 01 ▲](https://user-images.githubusercontent.com/20324844/74615304-cf2eac80-511f-11ea-9e91-dfa2c32df5ae.gif)
You may want o see a codepen but I can probably share the dev URL of our production site for your reference

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
