### ISSUE TITLE
when the element's position has changed, the tour's position don't change at the same time

### ISSUE THREAD

**Issue by wmo123** [kamranahmedse/driver.js#222]
when the element's position has changed, the tour's position don't change at the same time; then,i  try to use ' driver.refresh()' , but it doesn't work...i don't know why ???
![image](https://user-images.githubusercontent.com/47963460/74815985-340f2000-5335-11ea-8be9-656f0bf83bd7.png)

**Comment by marzsv** [comment]
Were you able to solved this problem @wmo123 ?

**Comment by namangarg** [comment]
@kamranahmedse I think driver.refresh() is not public method and we cannot use it

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. You now have `refresh` method publicly available for use. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
