### ISSUE TITLE
It's possible to call moveNext when I click on driver-popover-item?

### ISSUE THREAD

**Issue by heliomsolivas** [kamranahmedse/driver.js#229]
I'm trying to trigger the moveNext function when the user clicks inside the popover chained to the highlighted element, is it possible? (I'm not using the default buttons inside the steps)

I tried to attach a click event inside driver-popover-item but sometimes the element doesnt exist yet

**Comment by aditi824** [comment]
I want to contribute to this issue.

**Comment by kamranahmedse** [comment]
This is now possible with v1.0

https://driverjs.com/docs/buttons/
