### ISSUE TITLE
close button is aways show

### ISSUE THREAD

**Issue by wangmin19861205** [kamranahmedse/driver.js#237]
my config is :
  this.driver = new Driver({
            animate: true, // Animate while changing highlighted element
            opacity: 0.75, // Background opacity (0 means only popovers and without overlay)
            allowClose: false, // Whether clicking on overlay should close or not
        })
close button is aways show

**Comment by wangmenghub** [comment]
我也有同样的问题

**Comment by vashugupta** [comment]
show me the code pointer

**Comment by paulocastellano** [comment]
I have this same problem.

**Comment by thiag73** [comment]
Not ideal, but you get get arround with some CSS.
The close button has class `driver-close-btn`.
So you could use some thing like
``` CSS
.driver-close-btn {
    display: none !important;
}
```
`!imporant` is used here to override the CSS that cames with driver.js .
