### ISSUE TITLE
driverjs when called looks like it will start the tour but it stops immediately, what could be interfering with driverjs?

### ISSUE THREAD

**Issue by asdrubalp9** [kamranahmedse/driver.js#239]
when I click the button to start the tour, the screen goes black like if it's going to start the tour but then all closes and it shows no errors.

this is the code:

    $(document).on('click', '#getHelp',function(e){	
        let steps2 = [                
                    {
                        element: ".nombreCurso",
                        popover: {
                        title: 'Title on Popover',
                        description: 'Body of the popover',
                        position: 'right'
                        }
                    }
                ]
                driver.defineSteps(steps2)
                driver.start();
    });

what could be interfering with driverjs?

**Comment by kamranahmedse** [comment]
You need to add `e.stopPropagation()`
```javascript
$(document).on('click', '#getHelp',function(e){	
  e.stopPropagation();

  let steps2 = [                
    {
      element: ".nombreCurso",
      popover: {
        title: 'Title on Popover',
        description: 'Body of the popover',
        position: 'right'
      }
    }
  ];

  driver.defineSteps(steps2)
  driver.start();
});
```

**Comment by daxeshgandhi-klevu** [comment]
Yes, works
