### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by andrew--r** [kamranahmedse/driver.js#24]
Hi! Thanks for a nice library.

I think it's accessibility could be significantly improved. Currently, when some element is highlighted, keyboard focus is not restricted within this element so you can press Tab and focus will move out of highlighted element bounds. As well, popover buttons are made of `<a>` so they are not clickable by pressing `Space`.

I see two potential improvements:

1. Create a focus trap on highlighted elements (see https://hackernoon.com/its-a-focus-trap-699a04d66fb5)
2. Use semantic markup for popover controls (e.g. `<button>` instead of `<a href="javascript:void(0)">`

**Comment by nille2000** [comment]
Really cool indeed! I’m also interested in looking into using this for accessibility reasons. My website - datorskolan.com - is targeting elderly people. This would be a great way of guiding them where to click!

**Comment by kamranahmedse** [comment]
Hey Andrew, thank you for the feedback. 

I have fixed the markup. But for the focus trap, we won't be adding it into the core of the library just yet but I am planning to add the plugin mechanism to make it easier to add additional functionality on top of it so to keep the original library light-weight. And then may be we will release a plugin for this.

Thanks

**Comment by Lucas-C** [comment]
Just FYI, accessibility is also the main criteria that prevents me from using this awesome lib.

A simple example: navigating through the example demo page only with the tab key. Outline is not set on elements, visual transitions do not happen as with the mouse...
