### ISSUE TITLE
No issues. Badabing Badaboom! 

### ISSUE THREAD

**Issue by halukkaramete** [kamranahmedse/driver.js#242]
Way to go Kamran! Great work!

Just a quick question... 
I thought it would be really cool to blur the background view of the web page... ( kind of like creating the frosted glass effect... ) I tried filter: blur(..px) but that did not do the effect I was after.

What do I need to add to CSS so that as you dim the background, whatever on the background gets that blurry, frosted glass effect? These guys ( https://texascreative.com/blog/frosted-glass-html-css-tweaks ) took it to the next level but it gives you the idea of what I mean by blur.

**Comment by kamranahmedse** [comment]
Thanks Haluk. You may try `backdrop-filter: blur(5px)` i.e.

```css
#driver-page-overlay {
}
```

**Comment by halukkaramete** [comment]
Looks pretty good...  Thanks...

[image: Screen Shot 2020-06-01 at 2.39.32 AM.png]
