### ISSUE TITLE
Wrong highlight position when element is inside a node with position: fixed

### ISSUE THREAD

**Issue by elciok** [kamranahmedse/driver.js#249]
I'm trying to use driver.js to build a product tour where some of the elements are in a navbar which has position = fixed to the top of the browser viewport.

When driver.js highlights this element, the popover and stage won't stay fixed at the same position when I scroll the page because they are using position: absolute. Its even worse when the page was scrolled before the highlight because it will use a position based on current scroll position but the auto scroll that happens after that will move the highlight to another spot in the page.

I have a simple example that demonstrates this issue:

https://codepen.io/elciok/pen/YzwJLXE

A fixed positioned element also causes the same problems as reported in this other issue: https://github.com/kamranahmedse/driver.js/issues/241. When I remove position: fixed, the stage doesn't cover the highlighted element with a white element.

Thank you!

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
