### ISSUE TITLE
If element is invisible/hidden, it should be skipped

### ISSUE THREAD

**Issue by paceband** [kamranahmedse/driver.js#25]
If element is invisible/hidden, it should be skipped

**Comment by kamranahmedse** [comment]
Hey thank you for suggesting but I don't think we need to add that to library. 

However you can easily achieve that by `onHighlightStarted` – check if the element received is visible, if not call `driver.next()`

**Comment by kapooramit** [comment]
@kamranahmedse : Would you please share how to use ```onHighlightStarted``` with ```driver.next()``` for this case. 

I have the following demo.js and an element ( #3 - pdf_button) is hidden intentionally on some pages. What do I need to add here to make it skip the element if it is hidden. 

```
//Defines driver for all calls
const driver = new Driver({
  className: 'scoped-class',        // className to wrap driver.js popover
  animate: false,                    // Whether to animate or not
  opacity: 0.75,                    // Background opacity (0 means only popovers and without overlay)
  padding: 10,                      // Distance of element from around the edges
  allowClose: false,                 // Whether the click on overlay should close or not
  overlayClickNext: false,          // Whether the click on overlay should move next
  doneBtnText: 'Done',              // Text on the final button
  closeBtnText: 'Close',            // Text on the close button for this step
  stageBackground: '#ffffff',       // Background color for the staged behind highlighted element
  nextBtnText: 'Next →',              // Next button text for this step
  prevBtnText: '← Previous',          // Previous button text for this step
  showButtons: true,               // Do not show control buttons in footer
  keyboardControl: true,            // Allow controlling through keyboard (escape to close, arrow keys to move)
  scrollIntoViewOptions: {block:"top"},        // We use `scrollIntoView()` when possible, pass here the options for it if you want any
  onHighlightStarted: (Element) => {}, // Called when element is about to be highlighted
  onHighlighted: (Element) => {},      // Called when element is fully highlighted
  onDeselected: (Element) => {},       // Called when element has been deselected
  onReset: (Element) => {},            // Called when overlay is about to be cleared
  onNext: (Element) => {},                    // Called when moving to next step on any step
  onPrevious: (Element) => {},                // Called when moving to previous step on any step
});
 
//Start listening for click on the on the tour button and move forward when it happens. 
document.getElementById('launchtour')
        .addEventListener('click', function(event) {
          event.stopPropagation();

// Define the tour steps if the button is clicked. 
driver.defineSteps([
  {
    element: '#launchtour',
    popover: {
      title: 'Welcome to the Online Help Tour!',
      description: 'Watch this tour...',
      position: 'left',
    nextBtnText: 'okay, Start!'	
    }
  },
  {
    element: '#sidebar',
    popover: {
      title: 'Access the Tree',
      description: 'Browse the complete docs...',
      position: 'right'     
    }
  },
  {
    element: '#pdf_button',
    popover: {
      title: 'Create PDFs',
      description: 'Create PDFs ...',
      position: 'left'
    }
  },
  {
    element: '#selectglobe',
    popover: {
      title: 'Switch ',
      description: 'Select any of the ...',
      position: 'left'
    }
  },
  ]);

// Launch the tour if the button is clicked. 
driver.start();

});
```

**Comment by kapooramit** [comment]
Here is what worked. I replaced the code for ```onHighlightStarted``` with the following:
```onHighlightStarted: (Element) => {
    								if ((Element.visibility === "hidden")) {driver.next(); }
                                   }, // Called when element is about to be highlighted
```

**Comment by larissamasson** [comment]
I tried to use it - and and it didn't work:

onHighlightStarted: (Element) => {
        if (!$(Element.getNode()).is(':visible')) {
          if(driver.hasNextStep()){
            driver.moveNext();
          }
        }
      }
I tested moveNext() alone and it works fine, and I tested onHighlightStarted witih if (!$(Element.getNode()).is(':visible')) an it works fine to, but together it generates an infinite looping = (

**Comment by nxmndr** [comment]
This works with a timeout but unfortunately it allows to go back and shows an incorrect step number. I didn't check internal code but I assume the actual steps or their number cannot easily be determined beforehand, so in order to be fully coherent you should hide step number and Prev button.

You can also use onHighlighted and no timeout but it is slower. Weird.

```
onHighlightStarted(element) {
  if (! element) {
    setTimeout(_ => driverObj.moveNext(), 50)
  }
}
```

**Comment by klentgalimbas** [comment]
> This works with a timeout but unfortunately it allows to go back and shows an incorrect step number. I didn't check internal code but I assume the actual steps or their number cannot easily be determined beforehand, so in order to be fully coherent you should hide step number and Prev button.
> 
> You can also use onHighlighted and no timeout but it is slower. Weird.
> 
> ```
> onHighlightStarted(element) {
>   if (! element) {
>     setTimeout(_ => driverObj.moveNext(), 50)
>   }
> }
> ```

this works. but it broke the previous button of the next step
