### ISSUE TITLE
driver.moveNext() api call doesn't trigger onNext

### ISSUE THREAD

**Issue by mousanerdit** [kamranahmedse/driver.js#253]
In order to be able unit test onNext I need to trigger onNext using moveNext and movePrevious methods but callbacks just trigger by clicking on next and previous buttons

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
