### ISSUE TITLE
Can't  select element which is created in the onNext hook

### ISSUE THREAD

**Issue by jawn-ha** [kamranahmedse/driver.js#255]
Hi, Thanks for your work, It's amazing
![image](https://user-images.githubusercontent.com/16000122/90951576-a2709e80-e48e-11ea-9202-cf395723be0e.png)
In your Docs, I thought I can create an element in the `onNext` hook and choose it on the next step. But when I tried to do this, someting goes wrong

The example is here https://codesandbox.io/s/wonderful-meadow-bitik?file=/src/components/HelloWorld.vue
you can refesh page check the effect

**Comment by johnkmzhou** [comment]
The documentation is misleading. The library doesn't really support dynamic elements. #162

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
