### ISSUE TITLE
Driver start does not working

### ISSUE THREAD

**Issue by keke1123** [kamranahmedse/driver.js#258]
I create this sample but driver does not working well.

`<!DOCTYPE html>
<html lang="ko">

<head>
    <link rel="stylesheet" href="https://unpkg.com/driver.js/dist/driver.min.css">
    <script src="https://unpkg.com/driver.js/dist/driver.min.js"></script>
</head>

<body>
    <div id="aaaa" style="height: 100px;width:100px;background-color: red;"></div>
    <div id="bbbb" style="height: 100px;width:100px;background-color: blue;"></div>
    <div id="cccc" style="height: 100px;width:100px;background-color: black;"></div>
    <button onclick="r()">cccccc</button>
    <script type="text/javascript">
        const driver = new Driver({ animate: true, opacity: 0.75 });

        function r() {
            console.log(driver);
            // Define the steps for introduction
            driver.defineSteps([
                {
                    element: '#aaaa',
                    popover: {
                        className: 'first-step-popover-class',
                        title: 'atitle',
                        description: '11111',
                        position:'right'
                    }
                },
                {
                    element: '#bbbb',
                    popover: {
                        title: 'btitle',
                        description: '22222',
                        position:'right'
                    }
                }
            ]);
            driver.start();
        }
    </script>
</body>`

I can't see popover when I run this code and click button.
this code works just toggle dark background.
what is wrong this code?

**Comment by keke1123** [comment]
html code
`
    <div id="aaaa" style="height: 100px;width:100px;background-color: red;"></div>

    <div id="bbbb" style="height: 100px;width:100px;background-color: blue;"></div>

    <div id="cccc" style="height: 100px;width:100px;background-color: black;"></div>

    <button onclick="r()">cccccc</button>
`

**Comment by RoyXun** [comment]
You just forgot to call `event.stopPropagation()` .

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. No need for `stopPropagation` any more. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
