### ISSUE TITLE
Define buttons' text in the Driver Options instead

### ISSUE THREAD

**Issue by paceband** [kamranahmedse/driver.js#26]
For each step, it it possible to change to buttons' text:
```
const stepDefinition = {
  element: '#some-item',        // Query selector for the item to be highlighted
  popover: {                    // There will be no popover if empty or not given
    title: 'Title',             // Title on the popover
    description: 'Description', // Body of the popover
    showButtons: false,         // Do not show control buttons in footer
    doneBtnText: 'Done',        // Text on the last button
    closeBtnText: 'Close',      // Text on the close button
    nextBtnText: 'Next',        // Next button text
    prevBtnText: 'Previous',    // Previous button text
  }
};
```
In my opinion, it would be more logical to define them in the Driver Options, no? Or at least in both places...

**Comment by moghya** [comment]
@paceband do you mean keeping a default `nextBtnText` that is passed in Driver Options and override it as and when `nexBtnText` is passed in popover options?

**Comment by moghya** [comment]
@paceband it is possible to pass options for popover in  Driver options. 
Please try following way
```
new Driver({
    animate: true,
    opacity: 0.8,
    padding: 5,
    showButtons: true,
    nextBtnText: 'default text to be used for next button here'

  });
```

if you have any other question post it here or if it solves the thing please close this issue, thanks.

**Comment by moghya** [comment]
@paceband yea, can you please close this issue.

**Comment by kamranahmedse** [comment]
Added to the docs, thank you for reporting. 
Thanks @moghya
