### ISSUE TITLE
Define a custom class for highlighted elements

### ISSUE THREAD

**Issue by ejromero1990** [kamranahmedse/driver.js#262]
Does anyone know how to achieve it? And if is possible define a custom class for each element individually

**Comment by kamranahmedse** [comment]
We now add `driver-active-element` to the active element.

Also, we just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
