### ISSUE TITLE
[Feature request] Support custom button style

### ISSUE THREAD

**Issue by ChouJoe** [kamranahmedse/driver.js#266]
hey， i did not find any API or Property that support to modify the style of button
such as ‘next’、‘close’， and i want to make the style of button  Consistently with web style。

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. Please have a [look at the theming docs](https://driverjs.com/docs/theming/) and do let me know if you face any issues.
