### ISSUE TITLE
Problems with Highlight on Firefox

### ISSUE THREAD

**Issue by marcosguti** [kamranahmedse/driver.js#267]
@kamranahmedse I'm testing on firefox and Highlight seems wrong, looks like some problem with z-index,In chrome works fine 
![Screenshot_2020-11-04 Panel - Evaluacenter](https://user-images.githubusercontent.com/18442798/98110733-e6f8bd00-1e75-11eb-9e55-6093359c99a0.png)

**Comment by tector** [comment]
i have the same issue.
there seems to be an unmerged fix for this issue. see #293 

sadly this fix doesn't fix the issue for me :(

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
