### ISSUE TITLE
OnComplete and OnClose Implementation

### ISSUE THREAD

**Issue by aminemarref** [kamranahmedse/driver.js#268]
Hello,

Thanks for the library, it is awesome and just works. I am using it to implement a tutorial for first-time app visitors.

I have a question: How would I specify some action to be taken when the Driver's steps have completed or when the user closes the popover using the close button or by clicking outside it? This is useful to me because I create some HTML elements during the tutorial, and I want to erase them when the user finishes or aborts the tutorial.

For OnComplete, I am adding the "cleanup" code inside the onNext() function of the last step, and it is working. However, I do not know how to handle the abort action (clicking the close button or clicking outside the popover in the middle of the tutorial).

Thanks.

**Comment by mewalig** [comment]
Have you tried `onReset()`? it seems to do what you describe if you are using multiple steps and then `driver.start()`. I would imagine that you could delete your items inside `onReset`-- but I'm new to this library also so am interested to hear if either that doesn't work, or there's a better way.

**Comment by danrod96** [comment]
I can confirm that the `onReset()` functions works for that matter, thanks.

**Comment by ameeee** [comment]
Hi @aminemarref! 

open the constants.js folder found inside src/common and change line 43: to
`  <button class="${CLASS_CLOSE_BTN}" onClick="CloseT()">Close</button> `

if this alone didn't work go to driver.min.js and change driver-close-btn to include the onClick function like that:
`<button class="').concat("driver-close-btn",'" onClick="').concat("CloseT()",'" >Close</button>`

CloseT() will get triggered when you click on the close button, worked for me! :)

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. There is `onClose`, `onDestroyStarted` and `onDestroyed` hooks -- all having access to the current state which you can use to check if the walkthrough was completed or not. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
