### ISSUE TITLE
on animate false other elements apart from highlighted are also can be clicked even on overlay

### ISSUE THREAD

**Issue by chaitanya71998** [kamranahmedse/driver.js#269]
here it is even on highlight of sub container button even then you can also click either reset or highlight button
https://codesandbox.io/s/funny-heisenberg-91bzb
is it featured or need to change?

**Comment by w99910** [comment]
I had faced the same issue. 
This solved me.
[https://github.com/kamranahmedse/driver.js/issues/247#issuecomment-774016683](https://github.com/kamranahmedse/driver.js/issues/247#issuecomment-774016683)

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
