### ISSUE TITLE
Why is my dom element blocked and invisible?为什么我的dom元素被挡住了，看不见

### ISSUE THREAD

**Issue by miuqiang** [kamranahmedse/driver.js#278]
![image](https://user-images.githubusercontent.com/19277011/110882656-43d11c00-831d-11eb-95fd-8f1fd9bc32c0.png)
Why is my dom element blocked and invisible？
为什么我的dom元素被挡住了，看不见

**Comment by miuqiang** [comment]
fixed 的原因....

**Comment by w99910** [comment]
I'm having the same issue. How did you fix it?

**Comment by ATElephant** [comment]
你解决了？我用fixed也遇到同样问题

**Comment by miuqiang** [comment]
css属性，去掉fixed

**Comment by mvpyb** [comment]
> css属性，去掉fixed
但是如果不去掉fixed，又没有办法正常显示呢
