### ISSUE TITLE
on sophisticated html5 structure e.g. driver.start(stepNumber = 1); , driver do not focus the text but is empty

### ISSUE THREAD

**Issue by esklepy** [kamranahmedse/driver.js#281]
Hi, 
on screen dump in my project there is started tour from step 1 but the text area is empty.
when selecting prev and again next then it is ok.

![obraz](https://user-images.githubusercontent.com/9432412/113149351-2b289780-9233-11eb-999e-c66300b05a49.png)

the html and js is taken from https://github.com/kamranahmedse/driver.js and pasted to evato template.

the sandbox is https://i9dlv.csb.app/

html:
...
<pre>
<code>
<p>&lt;div id="third-element-introduction" class="section__example"&gt;<br />&lt;h4 id="first-element-introduction"&gt;Creating 
Feature Introductions&lt;/h4&gt;<br />&lt;p id="second-para-feature-introductions"&gt;
You can also make powerful feature introductions to guide the users<br />about the features. 
Just provide an array of steps where each step specifies an element to highlight.&lt;/p&gt;<br />&lt;p id="second-element-introduction"&gt;
Below is just a quick example showing you how to combine the steps in<br />introduction.&lt;/p&gt;<br />&lt;br&gt;<br />
&lt;a href="javascript:void(0);" class="mybtn2" id="run-multi-element-popovers" &gt;
Driver tour prevent move&lt;/a&gt;
<br />&lt;/div&gt;<br />...</p>

...

<script type="text/javascript">
                
  var step10=false;
   const dprevmov = new Driver({
            allowClose: false,
        });

        // Define the steps for introduction
        dprevmov.defineSteps([
          {
            element: '#first-element-introduction',
            popover: {
              title: 'Title on Popover',
              description: 'Body of the popover',
              position: 'left'
            }
          },
          {
            element: '#second-element-introduction',
            popover: {
              title: 'Title on Popover',
              description: 'Body of the popover',
              position: 'top'
            },
            onNext: () => {
              // Prevent moving to the next step

              if(step10==false){
              dprevmov.preventMove();
                }
              
              const lastActiveElement = dprevmov.getLastHighlightedElement();
              alert (lastActiveElement);
              // // Perform some action or create the element to move to
              // // And then move to that element
              // setTimeout(() => {
              //   driver.moveNext();
              // }, 4000);
            }
          },
          {
            element: '#third-element-introduction',
            popover: {
              title: 'Title on Popover',
              description: 'Body of the popover',
              position: 'right'
            }
          },
        ]);

        // Start the introduction
      //  dprevmov.start();

        $(".mybtn2").click(function(event){
          event.stopPropagation();
          if (dprevmov.isActivated) {
            dprevmov.reset(true);
          } dprevmov.start();
        });

$(document).ready(function () {
function readyFn( jQuery ) {
      if (dprevmov.isActivated) {
            dprevmov.reset(true);
          } dprevmov.start(1);
}

readyFn();

});

</script>
</code>
</pre>
In sandbox the html is stripped with images.

The tour start ok, on the contrary to my project , but after clicking the previous button not visible buttons!
maybe the problem is connected.

thank you for response to this problem.

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
