### ISSUE TITLE
moveNext() and movePrevious() should call the  `onNext` `onPrevious` handler if available   

### ISSUE THREAD

**Issue by whaley248** [kamranahmedse/driver.js#292]
`moveNext()` and `movePrevious() `should call the  `onNext` `onPrevious` handler if available  (currently only  `handleNext()` and `handlePrevious()` will call handler)

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. There are more simplified hooks which give you more control over the popover and the whole lifecycle. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
