### ISSUE TITLE
The highlighted element is not clickable

### ISSUE THREAD

**Issue by yewanji** [kamranahmedse/driver.js#296]
My project is based on the VUE + Element UI, and I found that using DriverJS in modal frames would cause highlighted elements to be unclickable. Examples are as follows
 <el-dialog title="封面识别"  :visible.sync="displayCoverDiscernModal" width="800px"
                 :close-on-click-modal="false" class="image-modal" >
         <el-button class="discernBtn" type="primary"
                    @click="doCropper">识别二维码
         </el-button>
      </el-dialog>
 let driver = new Driver({
          allowClose: false,
          doneBtnText: '完成',
          closeBtnText: '关闭',
          nextBtnText: '下一步',
          prevBtnText: '上一步',
          opacity:0.5,
          animate:false
        })
        let items = {
          element: '.discernBtn',
          popover: {
            title: '温馨提示',
            description: '请选择',
            position: "bottom"
          }
        }
        driver.highlight(items)

![image](https://user-images.githubusercontent.com/42515433/122547709-08a06080-d063-11eb-85c3-dcb21b811172.png)

**Comment by Sushil-azaas** [comment]
I am having the same problem. The buttons/elements inside Highlighted parts not clickable

**Comment by tector** [comment]
maybe related: #293

**Comment by aditi824** [comment]
I want to contribute to this issue.

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
