### ISSUE TITLE
click buttons in popover  not working

### ISSUE THREAD

**Issue by shengzhou1216** [kamranahmedse/driver.js#297]
click close/next button not working , but keyboard can control 'next'/ 'previous' move

**Comment by aditi824** [comment]
I want to contribute to this issue.
Kindly assign me.

**Comment by mitroo** [comment]
It seems that #150 is causing touch events to not bind/work how it should on mobile. https://github.com/kamranahmedse/driver.js/blob/4a0247ee25ba4f235bbf87434e9217c50619a1b8/src/index.js#L101

For me downgrading to 0.9.3 is the way to avoid this.

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
