### ISSUE TITLE
[custom-css] :: Override CSS of driver.js

### ISSUE THREAD

**Issue by azharakbar** [kamranahmedse/driver.js#299]
Hi team,

Would like to know how to override the CSS provided by driver.js to have our own CSS styles for stage, popup, buttons etc

Is this possible ?

Thank you

**Comment by azharakbar** [comment]
@kamranahmedse please help us
Thank you

**Comment by nseb** [comment]
+1

**Comment by Naren-hybreeder** [comment]
@azharakbar, I know the question is old.

I have added my answer here https://github.com/kamranahmedse/driver.js/issues/323


check it once and let me know if it is working or not for you.

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. It gives you more control over the styling. Please have a [look at the theming page](https://driverjs.com/docs/theming/) and do let me know if you face any issues.
