### ISSUE TITLE
driver overlay remove from DOM after mount

### ISSUE THREAD

**Issue by popuguytheparrot** [kamranahmedse/driver.js#306]
![myfile](https://im3.ezgif.com/tmp/ezgif-3-d222e26ef344.gif)

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
