### ISSUE TITLE
How to highlight multiple elements at the same time?

### ISSUE THREAD

**Issue by tector** [kamranahmedse/driver.js#310]
My usecase is, that i want to highlight a table column.. i mean the whole column, not only the header.

I can give every cell of the table column the same class - but only the first one will be highlighted.

I would expect and like to have the behaviour that every element with the given class is highlighted at the same time.

Anyone knows a workaround for this?

**Comment by weijing580** [comment]
+1

**Comment by kamranahmedse** [comment]
One way to accomplish this would be to position an invisible div on top of the whole column and target that in your tour. There are no plans on implementing that natively in driver.js since it will open up another set of questions e.g. where to show the tooltip etc.

**Comment by majid4466** [comment]
To highlight a table column you can use `colgroup` and `col`s. I have tried this and it works. 
[https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Basics#styling_with_col
](https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Basics#styling_with_col
)

**Comment by BenJackGill** [comment]
> One way to accomplish this would be to position an invisible div on top of the whole column and target that in your tour. There are no plans on implementing that natively in driver.js since it will open up another set of questions e.g. where to show the tooltip etc.

The has this feature [shepherdjs](https://www.shepherdjs.dev/ ) by including an `extraHighlights` property as seen [here](https://docs.shepherdjs.dev/api/step/interfaces/stepoptions/#extrahighlights) in their docs. The arrow points to the original element and the `extraHighlights` is just used for highlighting extra parts in addition to the original element where the arrow is pointed.

Would love to see something similar in driver.js

**Comment by jankapunkt** [comment]
I am using the 1.x hooks to dynamically change the additional element's z index:

```js
steps: [
 {
    ...,
    popover: {
          onHighlightStarted: () => {
            const el = $('li[data-key="current-tab"]')
            const zIndex = el.css('z-index')
            el.data('old-z-index', zIndex)
            el.css('z-index', 10001)
          },
          onDeselected: () => {
            const el = $('li[data-key="current-tab"]')
            const oldZIndex = el.data('old-z-index')
            el.css('z-index', oldZIndex)
          }
    }
  }
]
```

I am using this to also show the tab of a bootstrap nav.
