### ISSUE TITLE
electron-vue not use

### ISSUE THREAD

**Issue by sunjiaqi1999** [kamranahmedse/driver.js#311]
Used in electron-vue ,the highlighted part is a white block ,and the content you want to highlight is not displayed

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
