### ISSUE TITLE
How to intercept closing event?

### ISSUE THREAD

**Issue by Asgen** [kamranahmedse/driver.js#318]
onReset: () => null,              // When overlay is about to be cleared

I want to show additional info BEFORE closing a tour.

**Comment by cemo162** [comment]
I don't understand

**Comment by qq869217311** [comment]
Onreset will be triggered when the mask is closed，
Is there a way to click close，
I need to close the entire driver when I click Close

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. There are more simplified hooks which give you more control over the popover and the whole lifecycle. You are probably looking at one of `onClose`, `onDestroyStarted` or `onDestroyed`. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
