### ISSUE TITLE
Invalid typings file

### ISSUE THREAD

**Issue by sactor** [kamranahmedse/driver.js#32]
The index.d.ts typings file exports classes that aren't structured in the same way as the exports are in index.js. This makes it very difficult to use driver.js in a TypeScript project.

The index.d.ts also has missing return types for many functions (should be void if doesn't return anything) and attempts to use defaults which aren't allowed in typings.

It seems as if the typings file is created manually. You should either generate the typings file from source or don't include the typings file at all.

**Comment by kamranahmedse** [comment]
Hey thank you for reporting, you are right; they were written in hurry and were not tested. I have pushed the patch without them, till we fix it. Thanks.

**Comment by kamranahmedse** [comment]
Updated the type definitions, should be fine now in `0.3.3` could you please confirm?

**Comment by fjaguero** [comment]
Looks like "position" is missing in "PopoverOptions".

```
Type '{ element: string; popover: { title: string; description: string; position: string; }; }' is not assignable to type 'Step'.
Types of property 'popover' are incompatible.
Type '{ title: string; description: string; position: string; }' is not assignable to type 'PopoverOptions | undefined'.
Object literal may only specify known properties, and 'position' does not exist in type 'PopoverOptions | undefined'.
```

**Comment by kamranahmedse** [comment]
Fixed, should be fine now, thanks @fjaguero 

Closing this for now, please report/re-open if you still face any issues.

**Comment by CaitieBoeyens** [comment]
There are still some types missing. In the constructor for Position I get the following error

`613:21 Binding element 'left' implicitly has an 'any' type.
613:21 Binding element 'top' implicitly has an 'any' type.
613:21 Binding element 'bottom' implicitly has an 'any' type.
613:21 Binding element 'right' implicitly has an 'any' type.`
