### ISSUE TITLE
Can the highlighted area be disabled

### ISSUE THREAD

**Issue by forestxieCode** [kamranahmedse/driver.js#321]
Can the highlighted area be disabled?

**Comment by Kinco4TC** [comment]
try it:
`new Driver({
      ...
      onHighlighted: (el) => {
        const node = el.getNode() as HTMLElement;
        node.style.pointerEvents = 'none';
      },
      onDeselected: (el) => {
        const node = el.getNode() as HTMLElement;
        node.style.pointerEvents = 'all';
      },
    })`

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. It now applies `driver-active-element` to the highlighted element which you can use instead in CSS.

```css
.driver-active-element {
  pointer-events: 'none'
}
```

Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
