### ISSUE TITLE
Django wraper

### ISSUE THREAD

**Issue by iwalucas** [kamranahmedse/driver.js#329]
I created a simple Django wraper for this library, if anyone is interested.
https://github.com/iwalucas/django-driverjs

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. You should probably upgrade driver.js as it has a different API. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
