### ISSUE TITLE
Strange clipping effect on unhighlighted elements with z-index

### ISSUE THREAD

**Issue by yogat3ch** [kamranahmedse/driver.js#331]
Hi @kamranahmedse,
This is cross-posted from [JohnCoene/cicerone#45](https://github.com/JohnCoene/cicerone/issues/45) where it's resolved in this [comment](https://github.com/JohnCoene/cicerone/issues/45#issuecomment-1161929251). Seems like an easy fix on the driver.js side but I don't know if our fix will be flexible across other use cases. Can you take a look at it?

Hope this finds you well!
We're switching up the Cicerone guide after making a lot of modifications to the app that have changed selectors and the order or our guide. 
We've just started to encounter this phenomenon where elements that aren't currently highlighted suddenly disappear under the overlay. The unfortunate news is that I have no clue what's causing this and therefore can not reproduce it. 
The best I can do at this point is provide some screenshots of the phenomenon just in case you or someone else have encountered it. I've redacted some things since the app is not yet public but the issue should still be evident despite them.
This screenshot depicts how the step that highlights our info icon `.fa-info-circle` causes the clipping to occur. 
<img width="974" alt="Screen Shot 2022-06-17 at 8 04 54 AM" src="https://user-images.githubusercontent.com/32208821/174295421-b0476e40-d2ac-4f69-aa94-d7fbb25ed4a8.png">

This screenshot depicts what the full `absolutePanel` looks like when the `cicerone` overlay is dismissed.
<img width="986" alt="Screen Shot 2022-06-17 at 8 06 27 AM" src="https://user-images.githubusercontent.com/32208821/174295708-653b1cbd-57d5-41ad-a71a-d80ddd99ff36.png">

The first occurrence of the clipping happens at this step:

![Screen Shot 2022-06-17 at 8 13 01 AM](https://user-images.githubusercontent.com/32208821/174296098-ac61bb68-eb1d-4b6e-aef0-d248fed67c84.png)

Here's what the underlying thing should actually look like:
![image](https://user-images.githubusercontent.com/32208821/174296145-5a425560-a91d-4882-8418-dec497687c00.png)

A pattern I just recognized is that it appears to do the clipping when highlighting a non-ID selector, such as a class or compound selector. 
Of note, we have an `on_next` step that expands that element in the background between this step, and the step mentioned earlier. 
I thought that might be the issue, so I revised the cicerone to start with the `absolutePanel` expanded and that doesn't fix the issue, the clipping still occurs.

Any ideas will be much appreciated.

Update 2022-06-12 0843: It is also appearing that the steps don't advance any further when the elements that were previously collapsed are highlighted. The guide ends with a small highlight rectangle:
![image](https://user-images.githubusercontent.com/32208821/174300872-ac4a9541-3cff-48fc-b396-74630a53bd90.png)

Is cicerone finding the objects to highlight in realtime? Or is it making a mapping of the highlighted areas at initialization? If it's the latter, I can see how that will cause a number of issues with any dynamic elements. If it's the former, then I'm unsure as to why it's not finding the appropriate elements. This may be a separate issue.

An additional note, the content of the element is handled by a uiOutput and is not in the UI module directly.

**Comment by josias-r** [comment]
I ran into a zIndex issue too, and the `fixStackingContext` hacks were not applicable to my issues. Therefore I [ported driver.js and refactored it](https://josias-r.github.io/boarding.js/) to have it work with an alternative concept that is more stable and does not reply on an zIndex logic.

This library would mostlikely avoid running into the issues you are having

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
