### ISSUE TITLE
If you use this in the El dialog component in the elementui framework, the content will be overwritten. Is there a solution

### ISSUE THREAD

**Issue by ljgx** [kamranahmedse/driver.js#335]
If you use this in the El dialog component in the elementui framework, the content will be overwritten. Is there a solution

**Comment by 865077695** [comment]
el-dialog__wrapper {
  position: absolute !important;
}

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
