### ISSUE TITLE
is driver able to custom the appended element?

### ISSUE THREAD

**Issue by inoutw** [kamranahmedse/driver.js#338]
I check the source code , all the popver element is directly append to the root body, when I use it in micro app and get the style isolated, then the function and popver UI is collapsed, is the driver able to custom the appended element?
![image](https://user-images.githubusercontent.com/8959119/181467854-8ca0e18b-ec17-4082-8af6-e63e6b69cf4d.png)

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. There are more simplified hooks which give you more control over the popover and the whole lifecycle. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
