### ISSUE TITLE
怎么在点击关闭按钮，关闭整个程序。

### ISSUE THREAD

**Issue by qq869217311** [kamranahmedse/driver.js#339]
Onreset will be triggered when the mask is closed，
Is there a way to click close，
I need to close the entire driver when I click Close

**Comment by qq869217311** [comment]
在页面出现跳转时 遮罩也会关闭 就会触发onReset 方法 。
这样我无法知道是跳转页面 还是单纯的点击关闭按钮。
有什么办法获取用户点击关闭的事件吗？

**Comment by qq869217311** [comment]
点击下一步或上一步时如果是跳转路由（遮罩关闭了）的也会触发onReset   顺序为 onNext > onReset || onPrevious > onReset

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. There is `destroy()` method which can be used for this purpose. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
