### ISSUE TITLE
How to add a class to the overlay

### ISSUE THREAD

**Issue by BerQin** [kamranahmedse/driver.js#341]
I hope to add a custom class to the overlay to modify some special styles. At present, there seems to be no ability to provide this aspect. I hope to consider it, as well as the customization of other important areas, and even custom elements can be appended to the plugin element.

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. There are more hooks which give you more control over the popover and the whole lifecycle. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
