### ISSUE TITLE
Add `destroy` method API

### ISSUE THREAD

**Issue by xuexb** [kamranahmedse/driver.js#347]
In some scenarios, we may need to actively destroy Driver instances, and these events should also be unregistered.

https://github.com/kamranahmedse/driver.js/blob/4a0247ee25ba4f235bbf87434e9217c50619a1b8/src/index.js#L86-L103

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. We do have a `destroy` method. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
