### ISSUE TITLE
how can i use this driver on my angular project

### ISSUE THREAD

**Issue by think2code1** [kamranahmedse/driver.js#35]
i install npm install driver.js into project and when i try to create object of the driver on my page it just display code.

Example
![1](https://user-images.githubusercontent.com/24632190/37583760-a4b6dc12-2b78-11e8-9f09-3dd030e98147.png)

<div id="single-element-no-popover" class="section__example">
  <h4>Highlighting a Single Element – Without Popover</h4>
  <p class="zero-bottom">If all you want is just highlight a single element, you can do that simply by passing the
    selector</p>
  <a href="#" class="btn__run-demo" id="run-single-element-no-popover">Show Demo</a>
  <code class="javascript">const driver = new Driver();
    driver.highlight('#create-post');
  </code>
</div>

![2](https://user-images.githubusercontent.com/24632190/37583784-c6b60c48-2b78-11e8-9d20-1d08b5049779.png)

**Comment by kamranahmedse** [comment]
Hey, if you were thinking it would work like this then my personal advice honestly would be to drop angular and learn JavaScript first :)

But anyways, it looks like you are using angular-cli, in that case open `.angular-cli.json` and put the CSS path in the `styles` array i.e.

```
styles: [
        "../node_modules/driver.js/dist/driver.min.css",
]
```

And then in the `app.component.js`, import the Driver as follows 

```
import * as Driver from 'driver.js'
```

and then you can write a click binding and use that code in the binding.
