### ISSUE TITLE
How can I do something on the popover

### ISSUE THREAD

**Issue by yokiizx** [kamranahmedse/driver.js#350]
I haven't seen an api that can be used after the popover visible.
I want to add some doms and add `addEventListenr` on them, but when step changed, it will be losing efficacy

**Comment by mlisowsk** [comment]
You can specify an event listener for `onHighlighted`. It will be called after the focused Element is highlighted and the popover shown.
Do you plan to manipulate the highlighted element or the popover or some unrelated element?

Keep in mind that if you manipulate the DOM and change the layout you will need to call `driver.refresh()` to reposition the stage and popover.

If you `addEventListener` in onHighlighted you should also `removeEventlistener` that listener in the onDeselected handler.

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. It gives you more control over the popup DOM using `onPopoverRender` hook. Please have a [look at the docs](https://driverjs.com/docs/styling-popover/#demo-hook-theme) and do let me know if you face any issues.
