### ISSUE TITLE
highlight element not showing in  side navbar

### ISSUE THREAD

**Issue by mukesh-inoid** [kamranahmedse/driver.js#355]
highlight element not showing in side navbar. but other element showing in outside of navbar. @kamranahmedse if you have any solution please give me.
![Screenshot 2023-01-19 130040](https://user-images.githubusercontent.com/107191507/213381478-b9141744-22ee-45f7-9ea9-98a77221b5be.png)

**Comment by amitbhargav0404** [comment]
same problem please guided me how to solve this problems

**Comment by amitbhargav0404** [comment]
> you can add class after import driver.min.css
> 
> `.driver-highlighted-element { pointer-events: none; }`

add 
but its not work

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
