### ISSUE TITLE
The highlighted area scrolls

### ISSUE THREAD

**Issue by daiyuelin** [kamranahmedse/driver.js#357]
当页面设置overflow: auto;并且超出高度滚动时，高亮弹出框发生滚动
When the page is set to overflow: auto; When the height is exceeded, the highlighted pop-up box will scroll
<img width="1226" alt="截屏2023-02-07 19 56 40" src="https://user-images.githubusercontent.com/57993937/217239367-b50d57b3-2c15-458a-bb3e-6ec2220cd652.png">

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
