### ISSUE TITLE
setSteps() is not accepting any args - some inconsistency in function definition

### ISSUE THREAD

**Issue by kovvurisushma** [kamranahmedse/driver.js#359]
the current definition for setSteps() is not accepting any arguments, ideally setter should accept steps as argument. in `driver/index.js` it is defined correctly but in `index.d.ts` it is defined incorrectly.
current implementation
```
    public setSteps(): void;
```
I think it should be something like this:
```
public setSteps(steps: any): void;

```
is it intentional?

**Comment by kamranahmedse** [comment]
We just released [v1.0](https://github.com/kamranahmedse/driver.js/releases/tag/1.0.3) of driver.js which has been rewritten from the ground up. This issue should no longer exist. Please have a [look at the docs](https://driverjs.com/) and do let me know if you face any issues.
