### ISSUE TITLE
What is the browser compatibility?

### ISSUE THREAD

**Issue by yamikuronue** [kamranahmedse/driver.js#36]
Forgive me if I overlooked it, but I can't seem to find a browser compatibility chart or list? You say "all major browsers", but for someone worried about supporting IE, I'd appreciate being more specific about what newer features are being used (if any). Thanks!

**Comment by kamranahmedse** [comment]
I will put the browser compatibility in the readme; thank you for the reminder. 

In its current state, it **supports IE10+**. For IE-9 and below, we just need to [update](https://github.com/kamranahmedse/driver.js/blob/25c3a1cc32f6b4e12d18a4bcc7aec13c446b5b2f/src/index.js#L85) [some parts](https://github.com/kamranahmedse/driver.js/search?utf8=%E2%9C%93&q=classList&type=) after which it should be usable in IE-8 and 9 also.
