### ISSUE TITLE
Uncaught Error: There are no steps defined to iterate 

### ISSUE THREAD

**Issue by amitbhargav0404** [kamranahmedse/driver.js#360]
<!DOCTYPE html>
<html>
<head>
	<title>Feature Introduction using Driver.js</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/driver.js/0.9.8/driver.min.js" integrity="sha512-TMCPpR1wPPr92/7kiF88j9uTWczLpHyUTzt8sScGyN2btq/xWN22GjsdgNfUIMDtXV5WXUZ4s2OThcgpVxQv4w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/driver.js/0.9.8/driver.min.css" integrity="sha512-yQuTmOu0Rm68Udrrd2uqDvHc/xzvQxJoNzYgLn7SK+EpPuEKZu82S44D2G++HLiz6lhUShgJPOri7zvRTVtyZQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <style>
    /* Define the styles for the progress bar */
    progress {
      width: 100%;
      height: 16px;
      margin-top: 16px;
    }

    progress::-webkit-progress-bar {
      background-color: #f5f5f5;
      border-radius: 8px;
    }

    progress::-webkit-progress-value {
      background-color: #3498db;
      border-radius: 8px;
    }
  </style>
</head>
<body>
  <h1>Welcome to My Web Application</h1>

  <p>This is a brief tutorial on how to use some of the features of our web application.</p>
  <button id="start-tour">Start Tour</button>

  <div id="feature1" style="margin-bottom: 16px;">
    <h2>Feature 1</h2>
    <p>This is the first feature of the application.</p>
  </div>

  <div id="feature2" style="margin-bottom: 16px;">
    <h2>Feature 2</h2>
    <p>This is the second feature of the application.</p>
  </div>

  <div id="feature3" style="margin-bottom: 16px;">
    <h2>Feature 3</h2>
    <p>This is the third feature of the application.</p>
  </div>

  
  <progress id="progressBar" value="0" max="100"></progress>

  <script>
    // Define the steps of the feature introduction
  const steps = [
    {
      element: "#feature1",
      title: "Feature 1",
      description: "This is the first feature of the application.",
    },
    {
      element: "#feature2",
      title: "Feature 2",
      description: "This is the second feature of the application.",
    },
    {
      element: "#feature3",
      title: "Feature 3",
      description: "This is the third feature of the application.",
    },
  ];

  // Initialize a new Driver.js instance with the steps and options
  const driver = new Driver({
    steps: steps,
    allowClose: false,
    keyboardControl: true,
    backdropPadding: 10,
    onReset: () => {
      driver.start();
    },
  });

  // Add an event listener to start the feature introduction when the button is clicked
  document.getElementById("start-tour").addEventListener("click", () => {
    driver.start();
  });

  </script>
</body>
	
</html>

**its showing error for run multiples step **

**Comment by mlisowsk** [comment]
I don't think you can pass the steps in the options object of the Driver constructor. You have to call `driver.defineSteps(steps)` explicitly before you call `driver.start()`.
Also you need to wrap the title and description elements in a `popover` object like so:
```
{
    element: '#first-element-introduction',
    popover: {
      title: 'Title on Popover',
      description: 'Body of the popover',
      position: 'left'
    }
}
```

**Comment by amitbhargav0404** [comment]
thank you sir its wook

**Comment by eleven-net-cn** [comment]
> I don't think you can pass the steps in the options object of the Driver constructor. You have to call `driver.defineSteps(steps)` explicitly before you call `driver.start()`. Also you need to wrap the title and description elements in a `popover` object like so:
> 
> ```
> {
>     element: '#first-element-introduction',
>     popover: {
>       title: 'Title on Popover',
>       description: 'Body of the popover',
>       position: 'left'
>     }
> }
> ```

Give a simple example (Vue Composition API):

```ts
onMounted(() => {
  // call defineSteps in mounted, will be work fine.
  driver.defineSteps(steps);
  driver.start();
});
```
