### ISSUE TITLE
The boot process is confusing？

### ISSUE THREAD

**Issue by cccEric** [kamranahmedse/driver.js#367]
After the first boot process, the boot will be confused when the second boot process is repeated. I use both 1.0.3 and 1.0.4 versions, and write import "driver.js/dist/driver.css like this "; The editor prompts me that this css cannot be found?

**Comment by cccEric** [comment]
0.9.8 is ok

**Comment by kamranahmedse** [comment]
Can you please share how you are using it? Is it possible to provide a reproducible example?

**Comment by cccEric** [comment]
import { useEffect, useState } from 'react';
import { driver as ndriver } from 'driver.js';
import '../Beginner-guide/driver.css';
import '../Beginner-guide/driver.scss';
import { MyIcon } from '@/assets/icons/MyIcon';
import BeginnerDialog from '../dialog/BeginnerDialog';

// 声明状态变量的类型
type DriverState = ReturnType<typeof ndriver>;

export default function Index() {
  const [open, setOpen] = useState(false);
  const [driver, setDriver] = useState<DriverState | null>(null);

  useEffect(() => {
    if (!open && driver) {
      //  延迟出现driver
      setTimeout(() => {
        driver.drive();

        setTimeout(() => {
          BindClick(driver);
        }, 200);
      }, 200);
    }

    return () => {
      if (driver) {
        driver.destroy();
      }
    };
  }, [driver, open]);

  function BindClick(driver: DriverState | null) {
    // const pageoverlay = document.querySelector('#driver-page-overlay') as HTMLElement;

    // pageoverlay?.addEventListener('click', (e) => {
    //   e.preventDefault();
    //   e.stopPropagation();
    // });

    // const highlighted = document.querySelector('#driver-highlighted-element-stage') as HTMLElement;
    // // 创建伪元素并添加样式
    // let pseudoElement = document.createElement('div');
    // pseudoElement.classList.add('driver-click-blocker');
    // highlighted?.appendChild(pseudoElement);
    // highlighted?.addEventListener('click', (e) => {
    //   e.preventDefault();
    //   e.stopPropagation();
    // });

    // 使用事件委托处理按钮点击事件
    document.addEventListener('click', (event) => {
      const target = event.target as HTMLElement;
      if (target.classList.contains('next')) {
        if (driver?.isLastStep()) {
          console.log(1111);

          driver?.destroy();
          setDriver(null);
        } else {
          setTimeout(() => {
            driver?.moveNext();
          }, 100);

          // driver?.moveTo(2);
        }
      }
    });

    document.addEventListener('click', (event) => {
      const target = event.target as HTMLElement;
      if (target.classList.contains('ignore')) {
        driver?.destroy();
        setDriver(null);
      }
    });
  }

  return (
    <div>
      <div
        // ref={driverRef}
        className="rightguide"
        id="beginner-btn"
        onClick={() => {
          setOpen(true);
        }}
      >
        <MyIcon name="beginner" size={18} />
        <span>Beginner's guide</span>
      </div>
      {open && (
        <BeginnerDialog
          open={open}
          onClose={(v) => {
            if (v) {
              console.log('driver', driver);
              if (driver) {
                driver.destroy();
                setDriver(null);
              }
              const newDriver = ndriver({
                stagePadding: 10,
                doneBtnText: 'Configuration Now',
                nextBtnText: 'Next',
                prevBtnText: 'Ignore',
                showButtons: [],
                popoverClass: 'beginner-driver',
                overlayOpacity: 0.6,
                allowClose: false,
              });
              newDriver.setSteps([
                {
                  element: '#auto-collect-switch',
                  popover: {
                    // popoverClass: 'hahah',
                    title: 's',
                    description: `
                    <p>If the balance of the business address is not enough for a successful withdrawal, the auto asset collection will be activated. This will transfer assets to the current address to meet the withdrawal requirement.</p>
                      <div class="bottom-wrap">
                        <div class="step-num">2/5</div>
                        <div class="right-action">
                          <div class="ignore">Ignore</div>
                          <div class="custom-event next">Next</div>
                        </div>
                      </div>
                  `,
                    side: 'bottom',
                    align: 'end',
                  },
                },
                {
                  element: '#minimum-amount',
                  popover: {
                    title: 'Title on Popover',
                    description: `
                    <p>We can suggest the minimum Auto-Collection amount for you, but it's customizable to your needs. Any amount lower than the recommended minimum won't be collected. This enhances the user experience and saves costs.You can adjust the minimum at any time, the amount less than the minimum does not be collected.</p>
                      <div class="bottom-wrap">
                        <div class="step-num">3/5</div>
                        <div class="right-action">
                          <div class="ignore">Ignore</div>
                          <div class="custom-event next">Next</div>
                        </div>
                      </div>
                  `,
                    side: 'top',
                    align: 'end',
                  },
                },
                {
                  element: '#collect-btn',
                  popover: {
                    title: 'Title on Popover',
                    description: `
                    <p>In addition to auto asset collection, you also have the option to manually collect assets to better suit your business needs. 
                    Simply tap "Collect Asset" to start.</p>
                      <div class="bottom-wrap">
                        <div class="step-num">4/5</div>
                        <div class="right-action">
                          <div class="ignore">Ignore</div>
                          <div class="custom-event next">Next</div>
                        </div>
                      </div>
                  `,
                    side: 'top',
                    align: 'end',
                  },
                },
                {
                  element: '#configuration-btn',
                  popover: {
                    title: 'Title on Popover',
                    description: `
                    <p>After adding token, please tap on "Configuration Now" to configure the auto collect asset.</p>
                      <div class="bottom-wrap">
                        <div class="step-num">5/5</div>
                        <div class="right-action">
                          <div class="custom-event next">Configuration Now</div>
                        </div>
                      </div>
                  `,
                    side: 'top',
                    align: 'end',
                  },
                },
              ]);

              console.log('newDriver', newDriver.getConfig());
              setDriver(newDriver);
            } else {
              setDriver(null);
            }
            setOpen(false);
            // console.log(111);
          }}
        />
      )}
    </div>
  );
}
like this

**Comment by cccEric** [comment]
I confirm that the target element is on the current page

**Comment by cccEric** [comment]
<img width="448" alt="image" src="https://github.com/kamranahmedse/driver.js/assets/118706378/60329e54-b79e-4af6-ad4d-b1197f99c4c7">

**Comment by kamranahmedse** [comment]
Regarding CSS not found, please try removing `node_modules` and reinstalling the dependencies. It's hard for me to understand what you are doing in your codebase due to all the logic. Here's a [sample React application](https://stackblitz.com/edit/stackblitz-starters-v7jrea?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx,src%2Fstyle.css&title=React%20Starter) I created for you [and it is working](https://stackblitz-starters-v7jrea.stackblitz.io/). Please submit a trimmed down version in react reproducing the bug for me to look at.

**Comment by Hellottxo** [comment]
I have the same question

**Comment by Hellottxo** [comment]
> <img alt="image" width="448" src="https://user-images.githubusercontent.com/118706378/251529291-60329e54-b79e-4af6-ad4d-b1197f99c4c7.png"> I can't see css

I have the same question, have u solved?

**Comment by so1ve** [comment]
css files won't be display in suggestions.
