### ISSUE TITLE
The popover in driver.js does not appear correctly on a specific element.

### ISSUE THREAD

**Issue by irshad** [kamranahmedse/driver.js#370]
I am using `driver.js` in Svelte for some regions the first popover not coming in place. Check this repl https://svelte.dev/repl/51d08a84fda443b58a0e26a749bf9170?version=4.0.0

**Expected Behavior:**
The popover should appear on the targeted element specified by the CSS selector, accurately positioned according to the element's location.

**Actual Behavior:**
The popover appears centered on the page instead of being positioned on the targeted element.

**Comment by kamranahmedse** [comment]
I don't know much about Svelte so I am not sure how the rendering works but driver.js expects the item to be present for highlight. I wrapped the driver initialization in `window.setTimeout(() => {})` and it's working here:

https://svelte.dev/repl/5d78a89558bc424d86121e59f0b3e2b1?version=4.0.0
