### ISSUE TITLE
next.js can`t import styles

### ISSUE THREAD

**Issue by Devisione** [kamranahmedse/driver.js#372]
hi, i am try using the library with nextjs. when i add import css in globaly/component i recieve error "Package path ./dist/driver.css is not exported from package" when i use older version 0.9.7 package is work fine.

reproduce: https://codesandbox.io/p/sandbox/staging-architecture-x8r25p?file=%2Fpages%2Findex.js%3A8%2C27

**Comment by kamranahmedse** [comment]
This has been fixed in `1.0.5`. Please let me know if you are still facing any issues.
