### ISSUE TITLE
step-wise method overriding (onNextClick, onDeselected, etc) not working

### ISSUE THREAD

**Issue by alxmke** [kamranahmedse/driver.js#375]
When following [this example](https://driverjs.com/docs/async-tour/) for method overriding on a per-step basis, the function override seems to be ignored. When the next button is clicked on the step using the following code, none of the expected behavior happens; the console is never written to.

```
{   element: '#parent',
    popover: {
        title: 'Title for the Popover',
        description: 'Description for it',
    },
    onNextClick: () => {
        console.log("Is this function ever run?");
        driver.getActiveElement()?.remove();
        driver.moveNext();
    },
},
```

**Comment by kamranahmedse** [comment]
`onNextClick` has to be within the `popover` object. [Here's the working example.](https://stackblitz.com/edit/stackblitz-starters-k9hqrp?file=src%2FApp.js)
