### ISSUE TITLE
Disable transition animations when prefers-reduced-motion accessibility flag is set

### ISSUE THREAD

**Issue by gregexp** [kamranahmedse/driver.js#379]
Transition/fade animations should be disabled in driver.js when the visitor's `prefer-reduced-motion` flag is set in their operating system/web browser.

See https://www.smashingmagazine.com/2021/10/respecting-users-motion-preferences/

**Comment by kamranahmedse** [comment]
Thank you for the suggestion. This is [already configurable](https://driverjs.com/docs/configuration/#driver-configuration) using `animate` option. I might add this as a note in the documentation but I don't think we need to add the auto-detection in the library codebase.
