### ISSUE TITLE
Posible general problem with CDN head script

### ISSUE THREAD

**Issue by ferranJS** [kamranahmedse/driver.js#381]
I want to warn you about using the CDN script in Astro and possibly more frameworks in this issue.
I'm using Astro to build [this site](https://github.com/ferranJS/astro-tailwind-landing-0).
When adding a script to the tag that runs driver.js CDN code into an Astro component
```
<script src="https://cdn.jsdelivr.net/npm/driver.js@1.0.1/dist/driver.js.iife.js"></script>
```
Astro transforms the component into another js script which imports the script like this 
```
import "https://cdn.jsdelivr.net/npm/driver.js@1.0.1/dist/driver.js.iife.js"
```
This gives an error in the first line of the script
```
this.driver = this.driver || {};
```
```
Uncaught TypeError: Cannot read properties of undefined (reading 'driver')
    at driver.js.iife.js:1:18
```

I solved this by adding the script in the index.html as a _slot_ for the component that was being processed (which is kind of an ugly solution). The changes can be seen in [this commit](https://github.com/ferranJS/astro-tailwind-landing-0/commit/3e2803b2cb8cc5c1ca5ea49bdaa602a200a151b6)

I don't know if this is a problem you should address in any way but I hope it is helpful and can prevent problems in the future. 
If more information is needed, I'm eager to help.

**Comment by kamranahmedse** [comment]
Thanks @ferranJS 

I am not sure what we can do about it — `iife` generated by vite/rollup is meant to be imported using `script` tag instead of `import`. I don't know any frameworks other than Astro that manipulate the script tags in that manner so I don't think it's going to be an issue. We can leave a note in the documentation for this maybe.
