### ISSUE TITLE
[Feature Request] Disabling actions within highlighted element.

### ISSUE THREAD

**Issue by Donnelly-Earley** [kamranahmedse/driver.js#383]
Hello!

I enjoy using this library, I think it's very good. I would just like to ask if it is in the roadmap at all to include an option to disable any clicks within a highlighted element?

It's simple to work around not having this option in the library, but it certainly adds to the overall code base on my applications.

If this is already possible using the library on its own, then I apologize.

**Thank you!**

**Comment by kamranahmedse** [comment]
Added `disableActiveInteraction` configuration option in in [1.2.x](https://github.com/kamranahmedse/driver.js/releases/tag/1.2.0) — thank you!
