### ISSUE TITLE
Closing on mobile

### ISSUE THREAD

**Issue by baskettcase** [kamranahmedse/driver.js#39]
I tested on mobile since I hoped it worked well and it does look great! The only problem I see is that I can't seem to close the driver when I tap outside. Bug?

**Comment by kevincobain2000** [comment]
I have submitted a pull request #94 
You can try with your driver obj like the follow.

```
    var driver = new Driver({
        opacity: 0.65,
    });
    driver.window.addEventListener('touchstart', driver.onClick, false);
```
