### ISSUE TITLE
Setting allowKeyboardControl to false doesn't do anything

### ISSUE THREAD

**Issue by davidhan527** [kamranahmedse/driver.js#391]
I set `allowKeyboardControl: false` and I'm still able to move through the guided tour using the left and right arrow keys.

Here is the full configuration that I'm using:
```
    const driverObj = driver({
      showProgress: true,
      allowKeyboardControl: false,
      showButtons: ["next", "previous"],
      steps: [...]
    })
```

**Comment by kamranahmedse** [comment]
[Fixed in 1.2.x](https://github.com/kamranahmedse/driver.js/releases/tag/1.2.0) — thank you!
