### ISSUE TITLE
[Bug & Feature request]The close button will only be displayed after configuring the allowClose parameter

### ISSUE THREAD

**Issue by alanwhy** [kamranahmedse/driver.js#392]
Version: 1.1.0

Expectations:

- `allowClose` only controls whether to allow clicking on the mask layer to close
- There is a new parameter to control whether to display the close button

In addition, version 0.9. X has `closeBtnText` that can be used to set the style of the close button. The new version has been removed and I hope it can be restored, which is very useful for me

Although I can rollback to version 0.9. X, I found that I also need the `progressText` parameter to help me modify the progress style（Scylla and Charybdis😣）

Should the close button also default to the `destroy()` method?

**Comment by kamranahmedse** [comment]
This is intentional — the only purpose `close` button serves is to close the popover. Keeping the close button while `allowClose` is set to `false` is only going to create confusion in the usage. However, if you still want it, you can use the `onPopoverRender` [hook to add the close button](https://driverjs.com/docs/buttons#custom-buttons).

**Comment by alanwhy** [comment]
> This is intentional — the only purpose `close` button serves is to close the popover. Keeping the close button while `allowClose` is set to `false` is only going to create confusion in the usage. However, if you still want it, you can use the `onPopoverRender` [hook to add the close button](https://driverjs.com/docs/buttons#custom-buttons).

Okay, it is recommended to directly add a solution for modifying the `close` button using `onPopoverRender` in the example, so that more people can easily switch versions.

Thank you for your reply~

**Comment by alanwhy** [comment]
@kamranahmedse 
I may still have discovered a bug. When I customize the button, if I customize the `className`, my `click` event will not be triggered. If I change it to `id`, it will not exist. Here is the code I ran without any issues, but changing it to `className` will not work

```js
onPopoverRender: (popover, { config, state }) => {
  const closeBtn = document.createElement("div");
  closeBtn.id = "driver-popover-close-btn-custom";
  // closeBtn.className = "driver-popover-close-btn-custom";
  closeBtn.innerText = "跳过引导";
  popover.wrapper.appendChild(closeBtn);
  closeBtn.addEventListener("click", () => {
    driverObj.destroy();
  });
},
```
