### ISSUE TITLE
The demo's last popover image has broken.

### ISSUE THREAD

**Issue by likui628** [kamranahmedse/driver.js#393]
![image](https://github.com/kamranahmedse/driver.js/assets/90845831/c63be9c3-8f57-452c-9a07-5611de314003)

https://github.com/kamranahmedse/driver.js/blob/288c7deafb5fa0f7e8a6d5d98648a047eb2b2b27/docs/src/components/Examples.astro#L110

**Comment by kamranahmedse** [comment]
It's working fine for me

<img width="759" alt="image" src="https://github.com/kamranahmedse/driver.js/assets/4921183/5a601bcd-c4b3-4373-9984-53635ae9b302">
