### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Cookiery** [kamranahmedse/driver.js#394]
Hi @kamranahmedse ,
Thank you for this exciting open source product.
I use npm run build and encountered an error.

```
ERROR in ./node_modules/driver.js/dist/driver.js.mjs
Module parse failed: Unexpected token (16:4)
You may need an appropriate loader to handle this file type.
|     disableButtons: [],
|     overlayColor: "#000",
|     ...e
|   };
| }

```

**Comment by kamranahmedse** [comment]
Looks like an issue with your build config -- I can't really say much without looking at your setup. Could you provide a demo repository reproducing the issue?
