### ISSUE TITLE
Skip Buttons

### ISSUE THREAD

**Issue by ravisingh8v** [kamranahmedse/driver.js#396]
Give a closeBtnText property so we can customize the exit button text too. Because with a close button icon, users may be confused if it will close the entire tour or just the current step. If there is option to customize text like 'skip tour' or just 'skip' instead of close icon, it will be easier for users to understand that clicking on it will close the entire tour.

**Comment by kamranahmedse** [comment]
Thank you for opening the issue but the behavior of close icon is pretty standard. There are no plans to replace icon with the textual button.
