### ISSUE TITLE
`moveTo` api will create a full screen svg shadow

### ISSUE THREAD

**Issue by HomyeeKing** [kamranahmedse/driver.js#397]
can't click highlighted part if called `movedTo` api, because the svg draw the whole screen

**Comment by kamranahmedse** [comment]
It's working fine for me. Here's [the working example](https://stackblitz-starters-v7jrea.stackblitz.io/) ([code](https://stackblitz.com/edit/stackblitz-starters-v7jrea?file=src%2FApp.tsx)). Click `Activate` button to activate and then click `moveTo` to move to specific step. Could you provide a reproducing example?

**Comment by HomyeeKing** [comment]
![image](https://github.com/kamranahmedse/driver.js/assets/49113249/5fb3c888-14b2-4109-9d6d-9f12ce95aee5)

my  case is call `moveTo` directly

**Comment by kamranahmedse** [comment]
You should use `.drive(index)` instead with the index to start tour with. `moveTo` is used when the driver is already active.
