### ISSUE TITLE
Scroll issue on firefox

### ISSUE THREAD

**Issue by MehdiAlouafi** [kamranahmedse/driver.js#4]
Hey Ahmed, great work ! 

While on chrome the scroll is as smooth as ever on firefox it doesn't scroll at all but jumps to the target container

To reproduce simply do the Quick Tour on the latest version of Firefox

EDIT 👍 
After a bit of testing the native .scroll function on firefox does not animate but I did the trick by doing : 

```
let t = 0:
let interval = null;

interval = setInterval(() => window.scroll(0, t = t + 10), 15);

```

Do you think that this can be a good fix to implement for firefox @kamranahmedse ?

**Comment by dziugasmeskauskas** [comment]
@MehdiAlouafi I tried to reproduce the bug, however I could not. 

Using the latest Firefox version (58.0.2) on macOS.

**Comment by MehdiAlouafi** [comment]
My bad I wasn't on the latest version, just upgrade to your version @dziugasmeskauskas and it works smoothly. However on older version of firefox the scroll is buggy, not an issue I guess
