### ISSUE TITLE
Does it work for svg elements ? 

### ISSUE THREAD

**Issue by lakinmohapatra** [kamranahmedse/driver.js#40]
Does it work for svg elements ?

**Comment by kamranahmedse** [comment]
Yes it does. Below is the demo – I used Github's SVG logo in this snapshot

![image](https://user-images.githubusercontent.com/4921183/37744742-207ad9da-2d71-11e8-8d61-f88aa2ef1dd7.png)

**Comment by lakinmohapatra** [comment]
Thanks for the info.
