### ISSUE TITLE
Should be support element query selector

### ISSUE THREAD

**Issue by nghiepit** [kamranahmedse/driver.js#41]
Thanks for awesome work!

I saw on the to-do list "Create wrappers for Angular, Vue and React".
Maybe we will have to wait very long.

If you now support the element query selector then _driver.js_ easy integrate with any other library.

```js
driver.highlight({
    element: document.querySelector("#container"),
    stageBackground: 'blue'
});
```

**Comment by OClement** [comment]
See https://github.com/kamranahmedse/driver.js/pull/42

**Comment by kamranahmedse** [comment]
You can do that since `0.4.0`. Thank you for reporting.
