### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by daria2023** [kamranahmedse/driver.js#410]
// function ee(e) {
//   (a("allowKeyboardControl") ?? !0) && (e.key === "Escape" ? L("escapePress") : e.key === "ArrowRight" ? L("arrowRightPress") : e.key === "ArrowLeft" && L("arrowLeftPress"));
// }
the function ee is throwing error when importing the package like this:
Module parse failed: Unexpected token (208:30)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders;
after i commented this function , it seems all right? ps i am using it inside a vue project.

**Comment by TTANF1** [comment]
I think you and I have the same problem, like #409 , and i had a PR to fix it.
