### ISSUE TITLE
Facing Issue with Scroll

### ISSUE THREAD

**Issue by ravisingh8v** [kamranahmedse/driver.js#412]
I am facing the issue while the second step of element is in scrollable distance, the highlight of driver.js go to the 2nd step but the popover remains on the 1st step only.
Is there any thing that i am missing or its a real problem?

**Comment by kamranahmedse** [comment]
Can you please provide a reproducing example? It should work fine with scroll.

**Comment by ravisingh8v** [comment]
I didn't get you, I just disable the animation then only it work properly otherwise if the next element is above or below the viewport the highlight move there and also its scroll till some point but after that the popover stuck in between. my code is really very simple no additional logic i have written

**Comment by kamranahmedse** [comment]
Can you [reproduce it here](https://stackblitz.com/edit/stackblitz-starters-1prcgj?file=src%2FApp.js,src%2Fstyle.css,src%2Findex.js) and share a link with me? It's a bit difficult for me to help you without it.

**Comment by ravisingh8v** [comment]
sorry for being  too late here is i have [reproduce it here](https://stackblitz.com/edit/stackblitz-starters-afplvu?file=src%2FApp.js,src%2Fstyle.css,src%2Findex.js) please find and try to start the tour
