### ISSUE TITLE
Popover title does not support innerHTML

### ISSUE THREAD

**Issue by MrZordex** [kamranahmedse/driver.js#414]
While in the docs it clearly says it should:

  // Title and descriptions shown in the popover.
  // You can use HTML in these. Also, you can
  // omit one of these to show only the other.
  title?: string;
  description?: string;

**Comment by sovetski** [comment]
I confirm, @kamranahmedse thank you for fixing it! Do you know when you will release a new version? Because on NPM we still have the problem as it is not updated yet

**Comment by kamranahmedse** [comment]
This has been fixed in `1.3.0`
