### ISSUE TITLE
Feature request: onChange event

### ISSUE THREAD

**Issue by sovetski** [kamranahmedse/driver.js#418]
Hi, actually we have onNextClick and onPrevClick, but if we want to add a callback for both we can't, except duplicating our code to run it twice. Can you please add onChange event? If you are ok, I can do it too, if it will be merged off course

**Comment by kamranahmedse** [comment]
This looks like it should exist in the application rather than the library. Can you please [look at the configuration](https://driverjs.com/docs/configuration#driver-configuration) and see if you can use any other hooks; there are `onHighlighted` and `onDeselected` as well.
