### ISSUE TITLE
Self-dismiss or cue next on a timer

### ISSUE THREAD

**Issue by majid4466** [kamranahmedse/driver.js#425]
In some situations it would be a better user experience if the popover would self-dismiss (or go to the next step) after a specified time interval. To get this behavior, I am playing with some combination of adding a custom property to the step and using `onPopoverRender`. It would be a nice addition to have this in the API though.

**Comment by kamranahmedse** [comment]
Thank you for the suggestion but to keep the bundle size smaller there are no plans to add that.
