### ISSUE TITLE
Wrong arrow position for align center if the viewport width is below 490px

### ISSUE THREAD

**Issue by majid4466** [kamranahmedse/driver.js#429]
Over 490px all is good:

![Screenshot 2023-09-08 at 12-48-08 JS Bin](https://github.com/kamranahmedse/driver.js/assets/72784/05fab34b-f59f-46e2-96ef-5e9aa4bd716f)

Between 490 and 460 the arrow jumps to the start position:
![Screenshot 2023-09-08 at 12-48-51 JS Bin](https://github.com/kamranahmedse/driver.js/assets/72784/0784899b-fa5f-426e-b29f-bfc3ec4f4741)

Below 460px it jumps to the end position:
![Screenshot 2023-09-08 at 12-49-30 JS Bin](https://github.com/kamranahmedse/driver.js/assets/72784/21d0f751-69d0-44b2-9a79-a2d422cbcc55)

I have tested with Chrome, Firefox Developer Edition and Opera. 

Here is a jsbin: [https://jsbin.com/giwasuqeve/edit?html,js,output](https://jsbin.com/giwasuqeve/edit?html,js,output)

**Comment by kamranahmedse** [comment]
Duplicate https://github.com/kamranahmedse/driver.js/issues/406

**Comment by chanmathew** [comment]
@kamranahmedse It's not a duplicate though, there are enough space on both sides, for some reason it's forcing the arrow to align end when it's below that size, even if there is enough space to fit the entire popover with the arrow center aligned.
