### ISSUE TITLE
New Release For 1.3

### ISSUE THREAD

**Issue by kdumontnu** [kamranahmedse/driver.js#440]
I apologize if this isn't the right place for this, but I'm really excited about using Driver.js in my product. I need some of the new changes in 1.3 to pass our CI checks (specifically https://github.com/kamranahmedse/driver.js/pull/432), so I wonder if there is an ETA on a new release. If there's anything I can do to help please let me know.

**Comment by kamranahmedse** [comment]
Apologies for the late reply. Fixed in 1.3.1.
