### ISSUE TITLE
Allow popover position to be inside the highlight

### ISSUE THREAD

**Issue by dreadnip** [kamranahmedse/driver.js#47]
I'd love a negative/inset positioning option that display the popover inside the highlight container (for highlights that take up almost the entire screen).

**Comment by Hilal-r** [comment]
@kamranahmedse 
I'd like to do this if its relevant.

**Comment by kamranahmedse** [comment]
Thank you @Hilal-r for offering to help, I am sorry, I got really busy and wasn't able to look at any activity in this repository and thus missed your comment. I am looking at the library this weekend, doing the improvements and closing the issues. I will reach out for the help if needed :-)

**Comment by kamranahmedse** [comment]
@dreadnip this has been resolved in the latest release (0.9.2) – you can use `mid-center` position on the popover that will place it on top of the highlighted element as below:

![image](https://user-images.githubusercontent.com/4921183/52444405-b4efe500-2b41-11e9-958d-8cc563f21ecb.png)

Thanks!
