### ISSUE TITLE
Can this work with Canvas elements?

### ISSUE THREAD

**Issue by Penn0r** [kamranahmedse/driver.js#482]
I am using ChartJS and would like to highlight certain bars, or legend items. Is this possible?

If not, is it possible to provide a custom x,y position to Driver?

**Comment by xionnon** [comment]
@Penn0r 
It is not supported to get elements inside a canvas, such as bar. Have you tried using a transparent div to place it at a specific position?

**Comment by Penn0r** [comment]
That's exactly what I ended up trying in the end and it works fine.

If anybody else finds a similar need:
1) I used getBoundingClientRect() to get the chart container div's position.
2) ChartJS, via myChart.legend.legendHitboxes and lineWidths provided me with the position & size of the legend within the canvas itself.

Thanks for response!
