### ISSUE TITLE
Wrong positioning

### ISSUE THREAD

**Issue by thomasthiebaud** [kamranahmedse/driver.js#50]
I have some positioning problem using the latest version of the library. This code

```
const driver = new Driver({ padding: 0 });
driver.defineSteps([{
  element: '#company-profile-display-name-input',
  popover: {
    title: 'Title on Popover',
    description: 'Body of the popover',
    position: 'top',
  },
}]);
driver.start();
```

with this html elements

```
<div class="row">
  <div class="large-12 columns">
    <label>
      {{"b2bsettingsapp.companysettings.information.form_settings_displayname" | translate }}
      <input
        id="company-profile-display-name-input"
        type="text"
        ng-model="businessUnitDetails.displayName"
        strip-html
      />
    </label>
  </div>
</div>
```

render like this

![screen shot 2018-03-27 at 11 34 49](https://user-images.githubusercontent.com/3715715/37959579-bfabcadc-31b3-11e8-89b3-4595990ca477.png)

If I inspect the styles, there are correctly applied (not override by something else), but the `top` value seems wrong

**Comment by kamranahmedse** [comment]
hey thomas, could you possibly create a reproducing plunker or any public link?

**Comment by thomasthiebaud** [comment]
I will try to do that. I found that the positioning is wrong until I resize the window. Once I resize it, everything looks ok

**Comment by thomasthiebaud** [comment]
I found out why. It is an angular problem not related with the library

Starting `driver` once the DOM has finished rendering using this piece of code solved it.

```
$timeout(function () {
  //DOM has finished rendering
  driver.start();
});
```

**Comment by Juanperezc** [comment]
I have exactly de same problen with ionic 3 , the top position is wrong but when I click the popover , 
this seems to be arranged
