### ISSUE TITLE
Not able to add multiple steps using driver.js cdn

### ISSUE THREAD

**Issue by Harpreet2004** [kamranahmedse/driver.js#509]
I am trying to add tour in a website using driver.js cdn but since it offers highlights for an element, i am not able to add highlights for multiple elements. When i add steps, it says steps is not defined. In addition to that showButtons is also not working as expected.

### Expected Behaviour
I should be able to add multiple elements in steps array such that the user can take a tour.

### Cdn Version
1.0.1

### Code samples & details
```const driver = window.driver.js.driver;
 const driverObj = driver();

   driverObj.highlight({
     showProgress: true, // Optional, displays a progress bar
     showButtons: ['next', 'previous', 'close'],
     steps: [
       {
         element: "#idSettingPages",
         popover: {
           title: "Title 1",
           description: "Description for element 1.",
            side: "left", 
            align: 'start'
         }
       },
       {
         element: "#idAboutUs", // Target by class
         popover: {
           title: "Title 2",
           description: "Description for element 2.",
            side: "left",
            align: 'start'
         }
       },
     ]
   });
```

**Comment by BegenchDev07** [comment]
Heyy! I've faced this issue. My solution was to recompile and bundle it into one _js_ file. 
I simply took the content from this repo _/src_ folder and compiled using **esbuild** 
My command for **esbuild**
`esbuild driver.ts --bundle --format=esm --outfile=out.js`
this command should generate the **out.js** and **out.css** . Then i created another _js_ file let's name it as **my_wrapper.js** and imported **out.js** such as this. 
`import {driver} from './src/out.js';

window.addEventListener('DOMContentLoaded',(e)=>{
    // alert('hey')
    setTimeout(()=>{
        const steppies = [
            {
                element:'#root',            
                popover:{
                    title: 'Welcome to our engine !',        
                    description: `Use  📷 to move across / Use 🔍 to zoom`,        
                }
            },
            {
                element:'#Palette_camTumble',
                popover:{
                    title: 'Scroll',        
                    description: 'Use this to scroll across the map',        
                }
            },
            {
                element:'#Palette_camZoom',
                popover:{
                    title: 'Zoom',        
                    description: 'Use this to zoom inside the map',        
                }
            },
            {
                element:'#Palette_select',
                popover:{
                    title: 'Select',        
                    description: 'Use this to select an element',        
                }
            },
            {
                element:'#Palette_paint',
                popover:{
                    title: 'Paint',        
                    description: 'Use this to paint the map',        
                }
            },
            {
                element:'#menu',            
                popover:{
                    title: 'Welcome to our engine !',        
                    description: `Use  📷 to move across / Use 🔍 to zoom`,        
                }
            }
        ]
        // const driver = window.driver.js.driver;        
        const driverObj = driver({
            steps:steppies
        });
        driverObj.drive();
    },3000)
})
`
As a result this _js_ file is imported to html as a script with `type=module` such as this. 
`<script src="my_wrapper.js" type="module">
</script>`
