### ISSUE TITLE
[Feature] Themes

### ISSUE THREAD

**Issue by JouzaLoL** [kamranahmedse/driver.js#52]
Hi, would it be possible to support custom themes?
I've already customized the styles to fit the material style, it would be great if we could just create a theme (sass?) file and choose it during build time.

**Comment by JouzaLoL** [comment]
Example of my material-inspired theme:
![2018-03-29 19_11_28-greenshot](https://user-images.githubusercontent.com/10381200/38102975-40e2c40c-3385-11e8-8a28-45905e4ba5e8.png)
Changes made: decreased border radius, restyled buttons, some other small changes

**Comment by kamranahmedse** [comment]
Feel free to create a PR :)

Move the common styles to a base sass and then create the theme file and update the build to generate multiple CSS files.

**Comment by kamranahmedse** [comment]
Thanks, I will check

**Comment by kamranahmedse** [comment]
Hey @JouzaLoL, 

Thanks for the PR but thinking more about it, I think it is fine without theme support as anyone can still override the CSS after installing. Plus we don't want to keep maintaining the theme files.

Thanks though and sorry for the inconvenience.
