### ISSUE TITLE
[z-index / 3d transform] Highlighted element with any parent that have transform-style: preserve-3d property are not showing

### ISSUE THREAD

**Issue by jewels9** [kamranahmedse/driver.js#56]
As stated in the title, having any element that lives in a parent having transform-style: preserve-3d makes them not showed when highlighted by driver.js.

Reproduced test case is very straightforward :
```html
<div class="container">
    <span id="highlight_item">test</span>
</div>
```
```css
.container {
    transform-style: preserve-3d;
}
```
```javascript
const driver=new Driver({});
driver.highlight('#highlight_item');
```
[And here's is a jsfiddle](https://jsfiddle.net/jewels9/u98ckerm/)

I'm not really asking a fix for this issue as I've just removed the preserve-3d transform style of the parents when an item needs to be highlighted but I would love to understand what's going on. I guess there is something to do with the fact that z-index is not working as expected in the 3d space.

Anyway, thanks for this great plugin I've been loving using it so far.
Cheers,
Joris

**Comment by kamranahmedse** [comment]
Fixed in `0.3.7`, thank you for reporting.

[`transform` creates a stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context), which was disturbing the styles applied.
