### ISSUE TITLE
defineSteps can't restart

### ISSUE THREAD

**Issue by frankLife** [kamranahmedse/driver.js#57]
It seems something wrong when I restart the `defineSteps`. the mask just flashed and no pop appear.

**Comment by kamranahmedse** [comment]
Hey thanks for opening the issue. Unfortunately, I couldn't understand. 

Could you please provide a plunker?

**Comment by Cody0913** [comment]
I was running into a similar issue with the site I was working on. Turns out I should have read through the readMe more carefully as I had forgotten to add  `e.stopPropagation();` to my click handler. 

Hope this helps.

**Comment by schutze** [comment]
@frankLife @Cody0913 After working on this all day, I just read this issue and realized I ran into the same thing. I added ` e.stopPropagation();` as the first line in my on click binding and the Driver popovers appeared.  Thanks!
