### ISSUE TITLE
it's not vanilla.

### ISSUE THREAD

**Issue by sebbekarlsson** [kamranahmedse/driver.js#6]
from looking at the source code, you can tell quite quickly that it is not vanilla as said in the README

**Comment by kamranahmedse** [comment]
Didn't get you. Why is it not vanilla?

**Comment by sebbekarlsson** [comment]
@kamranahmedse 

I'm pretty sure `export` and `import` statements is an ES6 thing.

**Comment by MartinMuzatko** [comment]
Vanilla is standards compliant. Even newer browsers support `import` and `export` with esm modules.
Not vanilla is:  Dependent on jQuery, Coffeescript or Typescript.
