### ISSUE TITLE
Overlay: highlighted-element and stage-element: z-index in container with fixed position

### ISSUE THREAD

**Issue by Fhoeddinghaus** [kamranahmedse/driver.js#60]
If I have a **div with "position: fixed"** as a container and in it an element (e.g. a p element) like
`<div style="position: fixed; ..."><p id="selector"></p></div>`
and I try to highlight the p inside the div, then the **hightlight-stage will overla**y the p (and of course the div).
The z-index of the selected element won't work right, because of the parent-div.
You can see a demo at [my site](https://www.xefli.de/projects/mplan/sys/content/drivertest.php) (I also included at first normal examples for test reasons) and in the image below.

The only way I found to fix it with dev tools was putting "z-index: 99999999999" in the div, but thats not a really good solution, if there are multiple elements in the div...

<img width="988" alt="grafik" src="https://user-images.githubusercontent.com/4275444/38313093-a7b04cd4-3823-11e8-9421-f57adde616be.png">

**Comment by kamranahmedse** [comment]
Fixed in `0.5.0`. But you have to be using non-animated version for that.

```
const driver = new Driver({
    animated: false
});
```

![image](https://user-images.githubusercontent.com/4921183/38780417-0f6481d2-40d6-11e8-8655-9f80795b9fd4.png)

**Comment by makeupsomething** [comment]
For anyone who comes to this issue and gets confused the code should be 

```js
const driver = new Driver({
    animate: false
});
```

**Comment by Yahasana** [comment]
Oops, not work for bootstrap modal

**Comment by dmartensson** [comment]
For animate mode, could you recursively walk up the element stack and apply an overlay behind every fixed and lift the fixed element above.

That way the element you need would be hoisted so its visible while recursively hide everything else?

**Comment by 12chagit** [comment]
How can I set the hideTimer for my driver?

**Comment by Naren-hybreeder** [comment]
@kamranahmedse , I am also getting the same issue,  If I use animate version then I am getting the issue, If I use without animate then it's working. How to use animated version with the above issues?
