### ISSUE TITLE
Supporting an array of selectors

### ISSUE THREAD

**Issue by keul** [kamranahmedse/driver.js#77]
I've the need to create a tour that highlight a subset of DOM sibling elements.

Something like: `driver.highlight('.foo, .bar');`

I can't use a parent node because the scope is to not highlight other siblings.

The expected final result should be probably to highlight the minimal rect that contains all of the elements.

Do you think that this new feature would be difficult to be implemented?

**Comment by ineentho** [comment]
+1 This is a feature I'm looking for to. My use case is to highlight several menu items that are next to each other.

I'd say the expected api would be `driver.highlight([className | element, className | element...])`.

**Comment by keul** [comment]
I'm trying to work on this (not an easy task however!).
Any suggestion from @kamranahmedse is welcome!

**Comment by kamranahmedse** [comment]
Hey @keul, thank you for opening the issue. There are no plans to add that, it is going to need drastic changes. The best way to do that would be to add multiple steps i.e. each element having its own step.

**Comment by Jateyan** [comment]
so，have resoved demo like " driver.highlight('.foo, .bar');"?

**Comment by arvsr1988** [comment]
is there a way to select multiple elements? I would like to select the first four table heading (th) elements of a table.

**Comment by mclngl** [comment]
it's not optimal but I managed to get around this by doing like so 
```
tags.forEach((_, index) => {
      const driver = new Driver({
        allowClose: false,
        className: styles.Driver,
        opacity: 1,
        stageBackground: 'transparent'
      });
      driver.highlight(
        `.${styles.Filters} > .${styles.Tag}:nth-child(${index + 1})`
      );
  });
```

**Comment by keul** [comment]
> > @Jateyan in the end, due to other requirements not related to this missing feature, I switched to another library
> 
> which one did you choose?

@SubhrajitDG i think it was react-joyride (as I was in a React context at the time)
