### ISSUE TITLE
Highlights part of screen after resize

### ISSUE THREAD

**Issue by khalidadil** [kamranahmedse/driver.js#8]
I'm not sure exactly what is causing this issue, but when testing this on the website this is what I'm seeing in Chrome on OSX:
https://cl.ly/1A1n2N0p2c19/Screen%20Recording%202018-03-12%20at%2011.05%20AM.gif

**Comment by kamranahmedse** [comment]
Hi Khalid, thank you for reporting. It should be fixed now. Could you please verify?

**Comment by khalidadil** [comment]
hi Kamran, it looks like it's fixed to me! Thanks for getting this taken care of so quickly!

**Comment by kamranahmedse** [comment]
Great. Thanks :)
