### ISSUE TITLE
driver-page-overlay not created in non animated mode

### ISSUE THREAD

**Issue by makeupsomething** [kamranahmedse/driver.js#82]
If I use driver in non animated mode then `driver-page-overlay` does not get created. 

Is this expected behaviour?

**Comment by kamranahmedse** [comment]
Yes, it is on purpose. In the non-animated case it achieves the overlay using a higher outline on the stage so to avoid any stacking issues that are not handled in the animated case. 

Is there any issue?

**Comment by kamranahmedse** [comment]
Closing it for no response. I am not able to reproduce this, please provide a plunker and reopen this.

**Comment by makeupsomething** [comment]
Sorry for the lack of response here. It seems my issue was caused by some css interfering with driver. Outline was being set to none for `*` elements.

**Comment by AMITSINGH1** [comment]
> Can you check the CSS for `.driver-stage-no-animation`, if it has the outline properly being applied?
> 
> I will be able to debug it better if you could provide the plunker or URL to the project/page where you are using this

how to avoid behind element click
