### ISSUE TITLE
Make context of all callbacks as popover object 

### ISSUE THREAD

**Issue by Yahasana** [kamranahmedse/driver.js#83]
it'd be very convenient and elegant to access methods of popover object in the callback. e.g.
```
onHighlightStarted: function(element){
    const title = this.getTitleNode();    // this == popover object
}
```
see [commit](https://github.com/kamranahmedse/driver.js/commit/d63e19e32071ed5c03924cef93cf02005a7fdfc2?diff=unified)

**Comment by kamranahmedse** [comment]
I think it will be confusing to bind element's hooks to the popover. Hooks already receive the `element` object. Just call `element.getPopover()` to get the popover.
