### ISSUE TITLE
Win7/10 IE11: Not working as expected

### ISSUE THREAD

**Issue by imlinus** [kamranahmedse/driver.js#88]
I'm having some issues in IE11.

It's showing the first one, but I can't seem to go to the next step. The buttons aren't working.
I can close it by pressing on the overlay, but the overlay won't disappear.

Is anyone else having the same issues?

![bs_win10_ie_11 0](https://user-images.githubusercontent.com/2436222/39362784-f8735e5c-4a27-11e8-9057-d9616df259eb.jpg)

Cheers,

**Comment by ChriStef** [comment]
Don't know maybe this related https://github.com/kamranahmedse/driver.js/commit/470a705479208ac06a5c4d9297a6a737285dbc7f#commitcomment-28785794

**Comment by kamranahmedse** [comment]
@imlinus can you please check if the latest release fixed it? Thanks

**Comment by imlinus** [comment]
Absolutely perfect!! Thank you for such a quick help!
