### ISSUE TITLE
[Feature request] Detect direction of movement in the callbacks

### ISSUE THREAD

**Issue by 00cpxxx** [kamranahmedse/driver.js#96]
While stepping through a tour I do specific changes to the screen and then when the user presses Previous I have to undo the changes. So far I could not find a way to determine from the onDeselected if user is going forward or backward. Is that possible already?

If that is not possible yet my suggestion is to add a property to the Element in the callback stating the direction of the movement and, optionally, the element that is going to show next. Knowing the direction and not only the next element is important because the element may repeat and depending on the movement direction different things may happen.

This sort of extension could be added to the other callbacks as well.

**Comment by 00cpxxx** [comment]
I'm currently emulating such feature by watching both onDeselected and onHighlighted. So I store the deselected element and compare in the highlighted callback.

**Comment by 00cpxxx** [comment]
@Yahasana your patch made me realize the existence of the variable currentStep inside the driver object. For me that is mostly enough since I can now simply store that number and compare to the next number. 

But since the variable is not documented in the API I guess it is internal and should not be used.

**Comment by kamranahmedse** [comment]
Hey, you can do that with `onNext` and `onPrevious` callbacks available in `0.6.0`
