### ISSUE TITLE
Fixed position element targets are not handled correctly

### ISSUE THREAD

**Issue by grandynguyen** [kamranahmedse/driver.js#97]
Overlay and popover elements should have fixed positioning if the highlighted element has it's position fixed.

**Comment by SGoldenGraham** [comment]
I have a codepen example of this not working:
[Fixed position Codepen](https://codepen.io/SGoldenGraham/project/editor/AJGGKy)

**Comment by BrandonSchreck** [comment]
I have the same issue with bootstrap v3.3.5 .navbar-fixed-top, .navbar-fixed-bottom css class. If changed from fixed to absolute the element is highlighted correctly. However, this causes the navbar to scroll with the page instead of being a fixed element.

**Comment by kamranahmedse** [comment]
Duplicate of https://github.com/kamranahmedse/driver.js/issues/112

**Comment by jsivelopment** [comment]
Any solution of this issue?

**Comment by AndyLiHong** [comment]
Any solution of this issue?
