### ISSUE TITLE
New logo design

### ISSUE THREAD

**Issue by jraulhernandezi** [kamranahmedse/driver.js#98]
Hi, ¿are you interested in having a new logo design with a favicon and banner design for your readme at GitHub?

I could send you some ideas, what do you think?

**Comment by kamranahmedse** [comment]
Hey @jraulhernandezi thank you for offering to contribute but I think it is fine as it is. I have something in mind for that, I am just not getting enough time to do that. But I will reach out to you if need be. But Thanks :)
